od.reader.jsonp_data_listing(20130703, "race", ["ID", "Name", "Origin", "DescriptionAttribute", "Size", "SourceBook"], [
    ["race38", "Bladeling", "Natural", "Wis, Dex or Str", "Medium", "MotP, Dra419"],
    ["race67", "Bozak Draconian", "Natural Reptile", "Cha, Con or Str", "Medium", "Dra421"],
    ["race10", "Bugbear", "Natural", "Dex, Str", "Medium", "MM"],
    ["race41", "Bullywug", "Natural", "Con, Dex", "Medium", "MM2"],
    ["race14", "Changeling", "Natural Shapechanger", "Cha, Dex or Int", "Medium", "EPG"],
    ["race35", "Deva", "Immortal", "Wis, Cha or Int", "Medium", "PHB2"],
    ["race1", "Dragonborn", "Natural", "Cha, Con or Str", "Medium", "PHB, HotFK"],
    ["race16", "Drow", "Fey", "Dex, Cha or Wis", "Medium", "FRPG, HotFK"],
    ["race42", "Duergar", "Natural", "Con, Wis", "Medium", "MM2"],
    ["race2", "Dwarf", "Natural", "Con, Str or Wis", "Medium", "PHB, HotFL"],
    ["race3", "Eladrin", "Fey", "Int, Cha or Dex", "Medium", "PHB, HotFL"],
    ["race4", "Elf", "Fey", "Dex, Int or Wis", "Medium", "PHB, HotFL"],
    ["race33", "Genasi", "Elemental", "Int, Con or Str", "Medium", "FRPG"],
    ["race17", "Githyanki", "Natural", "Con, Int", "Medium", "MM"],
    ["race18", "Githzerai", "Natural", "Wis, Dex or Int", "Medium", "PHB3"],
    ["race19", "Gnoll", "Natural", "Con, Dex", "Medium", "Dra367"],
    ["race20", "Gnome", "Fey", "Int, Cha or Dex", "Small", "PHB2"],
    ["race21", "Goblin", "Natural", "Dex, Cha or Wis", "Small", "MM, DSH"],
    ["race54", "Gold Dwarf", "Natural", "Con, Str or Wis", "Medium", "NCS"],
    ["race37", "Goliath", "Natural", "Str, Con or Wis", "Medium", "PHB2"],
    ["race6", "Half-Elf", "Natural", "Con, Cha or Wis", "Medium", "PHB, HotFK"],
    ["race36", "Half-Orc", "Natural", "Dex, Con or Str", "Medium", "PHB2, HotFK"],
    ["race5", "Halfling", "Natural", "Dex, Cha or Con", "Small", "PHB, HotFL"],
    ["race60", "Hamadryad", "Fey", "Wis, Cha or Int", "Medium", "HotF"],
    ["race65", "Hengeyokai", "Fey Shapechanger", "Dex, Cha or Wis", "Medium", "Dra404"],
    ["race22", "Hobgoblin", "Natural", "Con, Cha or Int", "Medium", "Dra419"],
    ["race7", "Human", "Natural", "Any", "Medium", "PHB, HotFL, HotFK"],
    ["race46", "Kalashtar", "Natural", "Cha, Int or Wis", "Medium", "EPG"],
    ["race68", "Kapak Draconian", "Natural Reptile", "Dex, Cha", "Medium", "Dra421"],
    ["race43", "Kenku", "Natural", "Cha, Dex or Int", "Medium", "MM2, Dra411"],
    ["race23", "Kobold", "Natural Reptile", "Con, Cha or Dex", "Small", "DSH"],
    ["race64", "Llewyrr Elf", "Fey", "Int, Cha or Dex", "Medium", "Dra405"],
    ["race27", "Longtooth Shifter", "Natural", "Str, Wis", "Medium", "PHB2"],
    ["race24", "Minotaur", "Natural", "Str, Con or Wis", "Medium", "PHB3"],
    ["race56", "Moon Elf (Eladrin)", "Fey", "Int, Cha or Dex", "Medium", "NCS"],
    ["race50", "Mul", "Natural", "Con, Str or Wis", "Medium", "DSCS"],
    ["race25", "Orc", "Natural", "Con, Str", "Medium", "MM"],
    ["race61", "Pixie", "Fey", "Cha, Dex or Int", "Tiny", "HotF"],
    ["race30", "Razorclaw Shifter", "Natural", "Dex, Wis", "Medium", "PHB2"],
    ["race47", "Revenant", "Living Undead", "Dex, Cha or Con", "Medium", "Dra376, HoS"],
    ["race62", "Satyr", "Fey", "Cha, Con or Dex", "Medium", "HotF"],
    ["race26", "Shadar-kai", "Shadow", "Dex, Int or Wis", "Medium", "Dra372"],
    ["race52", "Shade", "Shadow", "Cha, Dex or Int", "Medium", "HoS"],
    ["race49", "Shardmind", "Immortal Construct", "Int, Cha or Wis", "Medium", "PHB3"],
    ["race55", "Shield Dwarf", "Natural", "Con, Str or Wis", "Medium", "NCS"],
    ["race57", "Sun Elf (Eladrin)", "Fey", "Int, Cha or Dex", "Medium", "NCS"],
    ["race66", "Svirfneblin", "Fey", "Wis, Con or Str", "Small", "DSH"],
    ["race51", "Thri-Kreen", "Natural", "Dex, Str or Wis", "Medium", "DSCS"],
    ["race8", "Tiefling", "Natural", "Cha, Con or Int", "Medium", "PHB, HotFK"],
    ["race69", "Tinker Gnome", "Natural", "Int, Con or Dex", "Small", "Dra422"],
    ["race53", "Vryloka", "Living Undead", "Cha, Dex or Str", "Medium", "HoS"],
    ["race28", "Warforged", "Natural", "Con, Int or Str", "Medium", "EPG"],
    ["race58", "Wild Elf", "Fey", "Dex, Int or Wis", "Medium", "NCS"],
    ["race44", "Wilden", "Fey", "Wis, Con or Dex", "Medium", "PHB3"],
    ["race59", "Wood Elf", "Fey", "Dex, Int or Wis", "Medium", "NCS"]
])