od.reader.jsonp_data_listing(20130703, "background", ["ID", "Name", "Type", "Campaign", "Benefit", "SourceBook"], [
    ["background698", "Aberrant Slayer", "Racial", "General", "Associated: Dungeoneering, Perception", "PsP"],
    ["background772", "Accidental Initiate", "Origin", "General", "Associated: Insight, Perception", "Dra398"],
    ["background163", "Accursed Lineage", "Legacy of Acererak", "General", "Associated: History, Intimidate, Religion. +2 Diplomacy and Intimidate against undead.", "Dra371"],
    ["background164", "Adventurer's Scion", "Legacy of Acererak", "General", "Associated: Arcana, History, Religion. Can reroll any monster knowledge checks.", "Dra371"],
    ["background251", "Aerenal", "Geography", "Eberron", "Associated: Arcana, Religion", "EPG"],
    ["background2", "Aglarond", "Campaign", "Faerûn", "Add Elven to languages known, add Perception to class skill, and +1 to Perception.", "FRPG"],
    ["background595", "Airspur", "Geography", "Faerûn", "+2 to Acrobatics and Diplomacy.", "Dun172"],
    ["background3", "Akanûl", "Campaign", "Faerûn", "Gain resist 2 cold, resist 2 fire, and resist 2 thunder.", "FRPG"],
    ["background4", "Amn", "Campaign", "Faerûn", "Add Streetwise and Thievery to class skill, and +1 to Streetwise and Thievery.", "FRPG"],
    ["background832", "Ancestral Speaker", "Racial", "General", "Associated: History, Nature", "Dra411"],
    ["background339", "Ancient", "Racial", "General", "Associated: Endurance, History", "Dra380"],
    ["background70", "Apprentice of Sinister Cabal", "Campaign", "Scales of War", "Add Arcana and Dungeoneering to class skill, and +1 to Arcana and Dungeoneering.", "Dra366"],
    ["background158", "Arcane Agent", "Society", "General", "Associated: Stealth, Streetwise", "AP"],
    ["background159", "Arcane Mercenary", "Society", "General", "Associated: Diplomacy, History", "AP"],
    ["background347", "Arcane Pariah", "", "General", "Associated: Diplomacy, Streetwise", "Dra381"],
    ["background160", "Arcane Refugee", "Society", "General", "Associated: Arcana, History", "AP"],
    ["background161", "Arcane Sentinel", "Society", "General", "Associated: Arcana", "AP"],
    ["background75", "Arcane Student Who Saw Too Much", "Campaign", "Scales of War", "Receive a +1 to saves to end effects that daze, stun, immobilize, or restrain.", "Dra366"],
    ["background162", "Arcane Tracker", "Society", "General", "Associated: Dungeoneering, Nature", "AP"],
    ["background252", "Argonnessen", "Geography", "Eberron", "Associated: Athletics, Arcana", "EPG"],
    ["background387", "Arkhosian Totem Rager", "Racial", "General", "Associated: History, Streetwise", "PHR:D"],
    ["background759", "Artist", "Occupation", "General", "Associated: Diplomacy, History", "Dra394"],
    ["background733", "Aspirant of the Watcher", "", "General", "Associated: Arcana, Nature", "Dra392"],
    ["background66", "Assassin", "Campaign", "Scales of War", "Add Arcana and Stealth to class skill, and +1 to Arcana and Stealth.", "Dra366"],
    ["background680", "Astronomer", "Occupation", "General", "Associated: Arcana, History", "PsP"],
    ["background465", "Athlete", "Occupation", "General", "Associated: Acrobatics, Athletics", "MP2"],
    ["background234", "Aundair (City)", "Geography", "Eberron", "Associated: Arcana, History", "EPG"],
    ["background233", "Aundair (Small village)", "Geography", "Eberron", "Associated: Endurance, Nature", "EPG"],
    ["background54", "Auspicious Birth", "Campaign", "Scales of War", "Substitute highest ability score for Constitution to determine initial hit points.", "Dra366"],
    ["background677", "Awakened", "Birth", "General", "Associated: Bluff, Intimidate", "PsP"],
    ["background705", "Back Alley Bravo", "Occupation", "General", "Associated: Intimidate, Stealth", "Dra390"],
    ["background729", "Baernor Scion", "", "General", "Associated: Diplomacy, History", "Dra392"],
    ["background769", "Balance-Seeker", "Campaign", "Dark Sun", "Associated: Arcana, Nature", "Dra396"],
    ["background5", "Baldur's Gate", "Campaign", "Faerûn", "Know one language, add the Streetwise skill to class skill, and +2 to Streetwise.", "FRPG"],
    ["background747", "Baldur's Gate (Shifter)", "Campaign", "Faerûn", "Add History to class skill. +2 bonus to History. Add Elven to known languages. Pass as Elf when not shifting.", "Dra394"],
    ["background622", "Balic - Legionary", "Geography", "Dark Sun", "Associated: Athletics, Streetwise, Giant", "DSCS"],
    ["background623", "Balic - Patrician", "Geography", "Dark Sun", "Associated: Athletics, Streetwise, Giant", "DSCS"],
    ["background624", "Balic - Silt Sailor", "Geography", "Dark Sun", "Associated: Athletics, Streetwise, Giant", "DSCS"],
    ["background531", "Banished from the Order", "Occupation", "General", "Associated: Acrobatics, Thievery, Supernal", "Dra385"],
    ["background823", "Barovian Escapee", "", "General", "Associated: Perception, Stealth", "DSH"],
    ["background292", "Barrister", "Occupation", "General", "Associated: Diplomacy, Intimidate", "Dra378"],
    ["background214", "Basilisk's Gaze", "House Medani", "Eberron", "Associated: Arcana, Perception", "EPG"],
    ["background708", "Battlefield Wonderworker", "Occupation", "General", "Associated: Arcana, Athletics", "Dra390"],
    ["background468", "Beggar", "Society", "General", "Associated: Bluff, Insight", "MP2"],
    ["background336", "Bereaved", "Psychology", "General", "Associated: Insight, Religion", "Dra380"],
    ["background558", "Berserker", "Racial", "General", "Associated: Athletics, Intimidate", "Dra386"],
    ["background724", "Berserker - Follower of Kord", "Berserker", "General", "Associated: Intimidate, Perception", "Dra392"],
    ["background370", "Besmirched Birthright", "Racial", "General", "Associated: History, Streetwise", "PHR:D"],
    ["background700", "Bestial", "Racial", "General", "Associated: Acrobatics, Athletics", "PsP"],
    ["background88", "Birth - Among Another Race", "Birth", "General", "Associated: A skill the other race gains a bonus to", "PHB2"],
    ["background89", "Birth - Blessed", "Birth", "General", "Associated: Insight, Religion", "PHB2"],
    ["background90", "Birth - Cursed", "Birth", "General", "Associated: Bluff, Religion", "PHB2"],
    ["background91", "Birth - Omen", "Birth", "General", "Associated: Arcana, History", "PHB2"],
    ["background92", "Birth - On Another Plane", "Birth", "General", "Associated: Arcana", "PHB2"],
    ["background93", "Birth - Prophecy", "Birth", "General", "Associated: History, Religion", "PHB2"],
    ["background820", "Blackstaff Apprentice", "", "Faerûn", "Associated: Dungeoneering, History, Nature, Religion", "Dra409"],
    ["background564", "Blademaster", "Society", "General", "Associated: Acrobatics, Insight, Elven", "Dra386"],
    ["background299", "Blazestone", "Geography", "General", "Associated: Athletics, Endurance, Giant, Primordial", "PP"],
    ["background300", "Bleakmire", "Geography", "General", "Associated: Endurance, Stealth, Draconic", "PP"],
    ["background825", "Blessed of Zargon", "", "General", "Associated: Dungeoneering, Endurance", "DSH"],
    ["background838", "Bloodblade Soldier", "Racial", "", "Associated: Athletics, Endurance", "Dra429"],
    ["background545", "Bloodstone Runehammer", "Geography", "Faerûn", "Associated: Dungeoneering, Perception", "Dun177"],
    ["background301", "Bloodtangle", "Geography", "General", "Associated: Heal, Nature, Draconic, Goblin", "PP"],
    ["background469", "Borderland Nobility", "Society", "General", "Associated: Diplomacy, History", "MP2"],
    ["background71", "Born Under a Bad Sign", "Campaign", "Scales of War", "Substitute highest ability score for Constitution to determine initial hit points.", "Dra366"],
    ["background773", "Born of Avandra's Presence", "Origin", "General", "Associated: History, Religion", "Dra398"],
    ["background835", "Bozak Draconian", "Racial", "", "Associated: Arcana, Diplomacy, Intimidate", "Dra421"],
    ["background359", "Brains", "Occupation", "General", "Associated: Bluff, Streetwise", "Dra381"],
    ["background280", "Brash Duelist", "Adventurers", "Faerûn", "Associated: Bluff, Intimidate", "Dra376"],
    ["background484", "Brawny Gnome", "Racial", "General", "Associated: Athletics, Endurance", "Dra384"],
    ["background785", "Bregan D'aerthe Spy", "Campaign", "Neverwinter", "Associated: Bluff, Dungeoneering, Stealth", "NCS"],
    ["background235", "Breland", "Geography", "Eberron", "Associated: Diplomacy, Insight", "EPG"],
    ["background479", "Bringers of Spring", "Racial", "General", "Associated: Arcana, History", "Dra384"],
    ["background302", "Broken Lands", "Geography", "General", "Associated: Endurance, Intimidate, Dwarven, Giant", "PP"],
    ["background498", "Broken, Beaten, Scarred", "Racial", "Dark Sun", "Associated: Endurance, Heal", "DSCS"],
    ["background35", "Brother in Battle", "Campaign", "Scales of War", "Add Endurance to class skill, and +3 to Endurance.", "Dra366"],
    ["background360", "Burglar", "Occupation", "General", "Associated: Athletics, Thievery", "Dra381"],
    ["background348", "Buried Alive (Dark)", "", "General", "Associated: Dungeoneering, Endurance", "Dra381"],
    ["background678", "Calamity", "Birth", "General", "Associated: Arcana, Insight", "PsP"],
    ["background6", "Calimshan", "Campaign", "Faerûn", "Gain resist 4 fire and a +5 to Endurance made due to thirst.", "FRPG"],
    ["background817", "Callidyrr Dragoon", "", "General", "Associated: Athletics, Diplomacy, Insight", "Dra405"],
    ["background471", "Camp Follower", "Society", "General", "Associated: Endurance, Stealth", "MP2"],
    ["background195", "Cannith Inventor", "House Cannith", "Eberron", "Associated: Arcana", "EPG"],
    ["background196", "Cannith Tinker", "House Cannith", "Eberron", "Associated: Streetwise, Thievery", "EPG"],
    ["background197", "Cannith Warforged", "House Cannith", "Eberron", "Associated: Diplomacy, Insight", "EPG"],
    ["background293", "Captive", "Occupation", "General", "Associated: Insight, Stealth, Draconic", "Dra378"],
    ["background217", "Caravan Scout", "House Orien", "Eberron", "Associated: Athletics, Perception", "EPG"],
    ["background408", "Carnival Performer", "Racial", "General", "Associated: Acrobatics, Athletics", "PHR:T"],
    ["background67", "Cat Burglar", "Campaign", "Scales of War", "Add Athletics and Thievery to class skill, and +1 to Athletics and Thievery.", "Dra366"],
    ["background665", "Cerulean Adepts", "", "General", "Associated: Arcana, Streetwise, Deep Speech", "PsP"],
    ["background701", "Chameleon", "Racial", "General", "Associated: Stealth", "PsP"],
    ["background379", "Champion of Bahamut", "Racial", "General", "Associated: Diplomacy, Intimidate", "PHR:D"],
    ["background587", "Changeling Imposter", "Racial", "General", "Associated: Bluff, Streetwise", "Dra388"],
    ["background608", "Channeled Fury", "Racial", "General", "Associated: Endurance, Intimidate", "Dra389"],
    ["background612", "Chaos Bound", "Racial", "General", "Associated: Arcana, Endurance", "Dra389"],
    ["background515", "Charlatan", "Racial", "Dark Sun", "Associated: Bluff, Streetwise", "DSCS"],
    ["background7", "Chessenta", "Campaign", "Faerûn", "When spend an action point to take an extra action, +1 to all rolls made during the extra action granted.", "FRPG"],
    ["background364", "Child of Fate", "", "General", "Associated: Nature, Insight", "Dra382"],
    ["background232", "Child of Two Worlds", "Birth", "Eberron", "Associated: choose from either region of your origin.", "EPG"],
    ["background477", "Child of the Wildlands", "Racial", "General", "Associated: Endurance, Nature", "Dra383"],
    ["background410", "Chimera Tribe Champion", "Racial", "General", "Associated: Athletics, Endurance", "PHR:T"],
    ["background388", "Chosen of the Spirit Drake", "Racial", "General", "Associated: Insight, Religion", "PHR:D"],
    ["background466", "Circus Performer", "Occupation", "General", "Associated: Acrobatics, Thievery", "MP2"],
    ["background571", "Citizen of Kiris Dahn", "", "General", "Associated: Dungeoneering, Streetwise", "HS1"],
    ["background736", "Civic Reformer", "Society", "General", "Associated: History, Streetwise", "Dra393"],
    ["background478", "Civilization's Herald", "Racial", "General", "Associated: Diplomacy, Insight", "Dra383"],
    ["background596", "Clan Kranos", "Racial", "General", "Associated: Athletics, Intimidate", "Dra389"],
    ["background597", "Clan Sentune", "Racial", "General", "Associated: Diplomacy, Streetwise", "Dra389"],
    ["background598", "Clan Thavok", "Racial", "General", "Associated: Dungeoneering, Stealth", "Dra389"],
    ["background504", "Clanblade", "Racial", "Dark Sun", "Associated: Insight, Streetwise", "DSCS"],
    ["background227", "Clandestine Courtier", "House Thuranni", "Eberron", "Associated: Bluff, Insight", "EPG"],
    ["background48", "Cloistered Priest", "Campaign", "Scales of War", "Add Religion to class skill, and +3 to Religion.", "Dra366"],
    ["background260", "Commissioned Officer", "Occupation", "Eberron", "Associated: Insight, Intimidate", "EPG"],
    ["background45", "Con Artist", "Campaign", "Scales of War", "Add Bluff and Thievery to class skill, and +1 to Bluff and Thievery.", "Dra366"],
    ["background681", "Con Artist (Psionic)", "Occupation", "General", "Associated: Bluff, Insight", "PsP"],
    ["background182", "Convert", "Divine", "General", "Associated: Insight, Religion", "DP"],
    ["background366", "Corellon Dedicate", "Racial", "General", "Associated: Arcana, Stealth", "Dra382"],
    ["background28", "Cormyr (General)", "Campaign", "Faerûn", "Add Insight to class skill, +2 to Insight, and +2 to saves against fear effects.", "FRPG"],
    ["background8", "Cormyr (Wheloon)", "Campaign", "Faerûn", "Add Thievery to class skill, gain a +2 to Thievery, and gain a +2 to saves against charm effects.", "FRPG"],
    ["background695", "Cosmopolitan Perspective", "Racial", "General", "Associated: Diplomacy, Streetwise", "PsP"],
    ["background679", "Created", "Birth", "General", "Associated: Arcana, Nature", "PsP"],
    ["background392", "Crimson Curse", "Racial", "General", "Associated: Heal, Streetwise", "PHR:T"],
    ["background61", "Crusading Zealot", "Campaign", "Scales of War", "+1 to saves until fail a saving throw, and then the is gone until rest.", "Dra366"],
    ["background814", "Crystalbrooker", "Geography", "General", "Associated: Endurance, Nature", "Beyond the Crystal Cave"],
    ["background52", "Cult Escapee", "Campaign", "Scales of War", "Add Arcana and Bluff to class skill, and +1 to Arcana and Bluff.", "Dra366"],
    ["background826", "Cult Survivor", "", "General", "Associated: Arcana, Athletics, Religion", "DSH"],
    ["background808", "Cultist", "", "General", "Associated: Stealth, Streetwise", "The Book of Vile Darkness"],
    ["background263", "Cultural Assimilator", "Racial", "Eberron", "Associated: Diplomacy, Insight", "EPG"],
    ["background613", "Cunning Hypnotist", "Racial", "General", "Associated: Bluff, Insight", "Dra389"],
    ["background165", "Curious Archeologist", "Legacy of Acererak", "General", "Associated: History, Perception, Thievery. first successful Thievery check to disable trap in a skill challenge grants an extra success.", "Dra371"],
    ["background340", "Cursed", "Racial", "General", "Associated: Intimidate, Stealth", "Dra380"],
    ["background361", "Cutpurse", "Occupation", "General", "Associated: Bluff, Thievery", "Dra381"],
    ["background9", "Dalelands", "Campaign", "Faerûn", "Can reroll any Nature.", "FRPG"],
    ["background749", "Dambrath (Shifter)", "Campaign", "Faerûn", "While riding a creature, can reroll any Acrobatics, Athletics, Endurance, or Stealth using the creature's skill.", "Dra394"],
    ["background240", "Darguun", "Geography", "Eberron", "Associated: Athletics, Endurance", "EPG"],
    ["background170", "Dark Apprenticeship", "", "General", "Associated: Bluff, History", "Dra374"],
    ["background349", "Dark Contract (Infernal)", "", "General", "Associated: Intimidate, Religion", "Dra381"],
    ["background345", "Dead One", "", "General", "Associated: Insight, Streetwise", "Dra380"],
    ["background777", "Dead Rat Deserter", "Campaign", "Neverwinter", "Associated: Intimidate, Stealth, Thievery", "NCS"],
    ["background604", "Deep Seer", "Racial", "General", "Associated: Arcana, Insight", "Dra389"],
    ["background831", "Deep Wastes", "Campaign", "Encounters", "Associated: Dungeoneering, Nature", "Web of the Spider Queen"],
    ["background572", "Defender of the Oppressed", "", "General", "Associated: History, Streetwise", "HS1"],
    ["background241", "Demon Wastes", "Geography", "Eberron", "Associated: Endurance, Religion", "EPG"],
    ["background199", "Deneith Bodyguard", "House Deneith", "Eberron", "Associated: Insight, Perception", "EPG"],
    ["background198", "Deneith Mercenary", "House Deneith", "Eberron", "Associated: History, Intimidate", "EPG"],
    ["background506", "Desert Miner", "Racial", "Dark Sun", "Associated: Dungeoneering, Nature", "DSCS"],
    ["background257", "Deserter", "Adulthood", "Eberron", "Associated: Endurance, Bluff", "EPG"],
    ["background719", "Desperate Loner", "Racial", "General", "Associated: Bluff, Insight", "Dra392"],
    ["background350", "Desperate Measures", "", "General", "Associated: Endurance, Heal", "Dra381"],
    ["background43", "Detective", "Campaign", "Scales of War", "Add Perception and Insight to class skill, and +1 to Perception and Insight.", "Dra366"],
    ["background102", "Deva - Brink of Corruption", "Racial", "General", "Associated: Intimidate, Stealth", "PHB2"],
    ["background101", "Deva - Brink of Enlightenment", "Racial", "General", "Associated: Arcana", "PHB2"],
    ["background103", "Deva - Forgotten Lifetime", "Racial", "General", "Associated: Endurance, Thievery", "PHB2"],
    ["background588", "Deva Regressor", "Racial", "General", "Associated: History, Perception", "Dra388"],
    ["background337", "Deviant", "Psychology", "General", "Associated: Intimidate, Stealth", "Dra380"],
    ["background783", "Devil's Pawn", "Campaign", "Neverwinter", "Associated: Bluff, Religion", "NCS"],
    ["background183", "Disbeliever", "Divine", "General", "Associated: Bluff, Insight", "DP"],
    ["background383", "Disciplined Soldier", "Racial", "General", "Associated: Athletics, Endurance", "PHR:D"],
    ["background311", "Disgraced", "Society", "General", "Associated: Arcana, Diplomacy", "PP"],
    ["background809", "Disgraced Noble", "", "General", "Associated: Bluff, Diplomacy", "The Book of Vile Darkness"],
    ["background699", "Disgraced Pragmatist", "Racial", "General", "Associated: Dungeoneering, Intimidate", "PsP"],
    ["background416", "Disgraced Scion", "Racial", "General", "Associated: Dungeoneering, Nature", "Dra383"],
    ["background184", "Divinely Inspired", "Divine", "General", "Associated: Insight, Religion", "DP"],
    ["background579", "Domain Refugee", "", "General", "Associated: Bluff, Stealth", "Dra387"],
    ["background10", "Dragon Coast", "Campaign", "Faerûn", "Can reroll any Insight.", "FRPG"],
    ["background389", "Dragon Totem Clan", "Racial", "General", "Associated: Nature, Religion", "PHR:D"],
    ["background323", "Dragon Totem Warrior", "Racial", "General", "Associated: Athletics, Endurance", "PP"],
    ["background228", "Dragon's Path", "House Thuranni", "Eberron", "Associated: Arcana, History", "EPG"],
    ["background376", "Dragon-Blooded Spellcaster", "Racial", "General", "Associated: Arcana", "PHR:D"],
    ["background377", "Dragon-Bound Arcanist", "Racial", "General", "Associated: Arcana, Intimidate", "PHR:D"],
    ["background371", "Dragonbonded Clan", "Racial", "General", "Associated: Arcana, Intimidate", "PHR:D"],
    ["background375", "Dragonborn - Arcane Mercenary", "Racial", "General", "Associated: History, Streetwise", "PHR:D"],
    ["background106", "Dragonborn - Brush with the Past", "Racial", "General", "Associated: History, Insight", "PHB2"],
    ["background104", "Dragonborn - Dishonored", "Racial", "General", "Associated: Bluff, Streetwise", "PHB2"],
    ["background105", "Dragonborn - Rare Egg", "Racial", "General", "Associated: Arcana, Religion", "PHB2"],
    ["background380", "Dragonborn Iconoclast", "Racial", "General", "Associated: Arcana, History", "PHR:D"],
    ["background589", "Dragonborn Madness", "Racial", "General", "Associated: Insight, Intimidate", "Dra388"],
    ["background625", "Draj - Calmec Scribe", "Geography", "Dark Sun", "Associated: Religion, Stealth, Abyssal", "DSCS"],
    ["background626", "Draj - Jasuan Knight", "Geography", "Dark Sun", "Associated: Religion, Stealth, Abyssal", "DSCS"],
    ["background627", "Draj - Pochte Trader", "Geography", "Dark Sun", "Associated: Religion, Stealth, Abyssal", "DSCS"],
    ["background541", "Driven into Hiding", "Racial", "General", "Associated: Bluff, Stealth, A language the imitated race speaks", "Dra386"],
    ["background715", "Driven to Vengeance", "Racial", "General", "Associated: Dungeoneering, History, Deep Speech, Draconic, Elven, Giant", "Dra391"],
    ["background242", "Droaam", "Geography", "Eberron", "Associated: Dungeoneering, Nature", "EPG"],
    ["background108", "Drow - Orphan", "Racial", "General", "Associated: Dungeoneering, Endurance", "PHB2"],
    ["background107", "Drow - Outcast", "Racial", "General", "Associated: Dungeoneering, Perception", "PHB2"],
    ["background556", "Dune Ride", "Racial", "General", "Associated: Endurance, Nature", "Dra386"],
    ["background11", "Durpar", "Campaign", "Faerûn", "+2 to all Perception.", "FRPG"],
    ["background750", "Durpar (Shifter)", "Campaign", "Faerûn", "Reroll any Dungeoneering. Add Goblin to known languages.", "Dra394"],
    ["background368", "Dusk Envoy", "Racial", "General", "Associated: Diplomacy, History", "Dra382"],
    ["background839", "Dust-Treader Skald", "Racial", "", "Associated: Diplomacy, Insight", "Dra429"],
    ["background111", "Dwarf - Ancestral Home Lost", "Racial", "General", "Associated: Nature, Perception", "PHB2"],
    ["background110", "Dwarf - Dedicated to an Ancestor", "Racial", "General", "Associated: Diplomacy, History", "PHB2"],
    ["background140", "Dwarf - Outcast", "Racial", "General", "Associated: Bluff", "PHB2"],
    ["background438", "Early Life - Child Prodigy", "Early Life", "General", "Associated: Athletics, History", "Dra383"],
    ["background437", "Early Life - Divine Companionship", "Early Life", "General", "Associated: Religion", "Dra383"],
    ["background436", "Early Life - Imprisoned", "Early Life", "General", "Associated: Athletics, Thievery", "Dra383"],
    ["background435", "Early Life - Invited Underground", "Early Life", "General", "Associated: Dungeoneering, Streetwise", "Dra383"],
    ["background429", "Early Life - Isolated", "Early Life", "General", "Associated: Perception", "Dra383"],
    ["background432", "Early Life - Kidnapped", "Early Life", "General", "Associated: Acrobatics, Stealth", "Dra383"],
    ["background434", "Early Life - Lost Everything", "Early Life", "General", "Associated: Endurance, Nature", "Dra383"],
    ["background431", "Early Life - Social Outcast", "Early Life", "General", "Associated: Bluff, Intimidate", "Dra383"],
    ["background433", "Early Life - Test Subject", "Early Life", "General", "Associated: Arcana, Thievery", "Dra383"],
    ["background430", "Early Life - Well-Loved", "Early Life", "General", "Associated: Diplomacy, Insight", "Dra383"],
    ["background325", "Earth Steward", "Racial", "General", "Associated: Endurance, History", "PP"],
    ["background12", "East Rift", "Campaign", "Faerûn", "Gain Deep Speech as an language, add Dungeoneering to class skill, and +2 to Dungeoneering.", "FRPG"],
    ["background114", "Eladrin - Drowscarred", "Racial", "General", "Associated: Dungeoneering, Heal", "PHB2"],
    ["background113", "Eladrin - Estranged Fey", "Racial", "General", "Associated: Endurance, Nature", "PHB2"],
    ["background112", "Eladrin - Noble Birth", "Racial", "General", "Associated: Intimidate, Nature", "PHB2"],
    ["background243", "Eldeen Reaches", "Geography", "Eberron", "Associated: Athletics, Nature", "EPG"],
    ["background38", "Eldritch Harlequin", "Campaign", "Scales of War", "Add Bluff and Thievery to class skill, and +1 to Bluff and Thievery.", "Dra366"],
    ["background115", "Elf - Fey Ally", "Racial", "General", "Associated: Arcana, Insight", "PHB2"],
    ["background117", "Elf - Urban Elf", "Racial", "General", "Associated: Streetwise, Thievery", "PHB2"],
    ["background116", "Elf - Wild Elf", "Racial", "General", "Associated: Acrobatics, Athletics", "PHB2"],
    ["background13", "Elfharrow", "Campaign", "Faerûn", "Add Athletics and Nature to class skill, and +1 to Athletics and Nature.", "FRPG"],
    ["background331", "Embalmer", "Occupation", "General", "Associated: Heal, Nature", "Dra380"],
    ["background767", "Empath", "Occupation", "General", "Associated: Diplomacy, Insight", "Dra395"],
    ["background693", "Enlightened Prodigy", "Racial", "General", "Associated: Heal, Religion", "PsP"],
    ["background261", "Enlisted Soldier", "Occupation", "Eberron", "Associated: Athletics, Endurance", "EPG"],
    ["background343", "Ennui", "Racial", "General", "Associated: Athletics, Religion", "Dra380"],
    ["background609", "Eternal Journey", "Racial", "General", "Associated: Athletics, Endurance", "Dra389"],
    ["background669", "Eternal Seekers", "", "General", "Associated: Arcana, Insight", "PsP"],
    ["background731", "Everwatch Conscript", "", "General", "Associated: Athletics, Perception", "Dra392"],
    ["background516", "Exiled Survivor", "Racial", "Dark Sun", "Associated: Endurance, Nature", "DSCS"],
    ["background702", "Exotic Appearance", "Racial", "General", "Associated: Diplomacy, Intimidate", "PsP"],
    ["background384", "Exotic Gladiator", "Racial", "General", "Associated: Acrobatics, Athletics", "PHR:D"],
    ["background533", "Experimental Prototype", "Racial", "General", "Associated: Athletics, Endurance", "Dra385"],
    ["background502", "Explorer of the World", "Racial", "Dark Sun", "Associated: Diplomacy, Heal", "DSCS"],
    ["background41", "Explorer/Guide", "Campaign", "Scales of War", "Learn an extra language, add Nature to class skill, and +2 to Nature.", "Dra366"],
    ["background271", "Extra Muscle", "Adventurers", "Faerûn", "Associated: Athletics, Insight", "Dra376"],
    ["background312", "Failed Thane", "Society", "General", "Associated: Diplomacy, Insight", "PP"],
    ["background709", "Fainéant Apprentice", "Occupation", "General", "Associated: Bluff, Stealth", "Dra390"],
    ["background710", "Faith Leech", "", "General", "Associated: Bluff, Stealth", "Dra390"],
    ["background744", "Fallen Star", "Racial", "General", "Associated: Bluff, Insight", "Dra393"],
    ["background185", "Family Tradition", "Divine", "General", "Associated: Diplomacy, History", "DP"],
    ["background521", "Feed the Debt", "Racial", "Dark Sun", "Associated: Intimidate, Stealth", "DSCS"],
    ["background330", "Feral Exile", "Racial", "General", "Associated: Arcana, Intimidate", "PP"],
    ["background512", "Feral Raider", "Racial", "Dark Sun", "Associated: Intimidate, Stealth", "DSCS"],
    ["background385", "Fervent Commander", "Racial", "General", "Associated: Bluff, Intimidate", "PHR:D"],
    ["background804", "Fey Beast Tamer", "", "General", "Associated: Arcana, Nature", "HotF"],
    ["background760", "Fey Blood", "Racial", "General", "Associated: Arcana, Perception, Elven", "Dra394"],
    ["background737", "Fey Exile", "Society", "General", "Associated: Arcana, History", "Dra393"],
    ["background689", "Fey Inheritor", "Racial", "General", "Associated: Arcana, Diplomacy", "PsP"],
    ["background393", "Fire in Your Veins", "Racial", "General", "Associated: Arcana, Intimidate", "PHR:T"],
    ["background666", "Fists of Zuoken", "", "General", "Associated: Acrobatics, Religion, Primordial", "PsP"],
    ["background273", "Flamescarred", "Adventurers", "Faerûn", "Associated: Arcana, History", "Dra376"],
    ["background186", "Followed a Cult", "Divine", "General", "Associated: Stealth, Streetwise", "DP"],
    ["background206", "Follower of Sahemi", "House Jorasco", "Eberron", "Associated: Heal, Nature", "EPG"],
    ["background503", "Follower of the Great One", "Racial", "Dark Sun", "Associated: Diplomacy, History", "DSCS"],
    ["background631", "Forest Ridge - Acclimated Trader", "Geography", "Dark Sun", "Associated: Nature, Perception", "DSCS"],
    ["background632", "Forest Ridge - Liberator", "Geography", "Dark Sun", "Associated: Nature, Perception", "DSCS"],
    ["background633", "Forest Ridge - Spirit Guided", "Geography", "Dark Sun", "Associated: Nature, Perception", "DSCS"],
    ["background40", "Forest Warden", "Campaign", "Scales of War", "Add Nature and Perception to class skill, and +1 to Nature and Perception.", "Dra366"],
    ["background628", "Forked Tongue - Merchant/Trader", "Geography", "Dark Sun", "Associated: Acrobatics, Endurance, Dwarven or Giant", "DSCS"],
    ["background629", "Forked Tongue - Ruin Gleaner", "Geography", "Dark Sun", "Associated: Acrobatics, Endurance, Dwarven or Giant", "DSCS"],
    ["background630", "Forked Tongue - Village Speaker", "Geography", "Dark Sun", "Associated: Acrobatics, Endurance, Dwarven or Giant", "DSCS"],
    ["background59", "Former Barbarian", "Campaign", "Scales of War", "Add Nature to class skill, and +1 to Nature.", "Dra366"],
    ["background827", "Former Cult Sympathizer", "", "General", "Associated: Bluff, Insight, Intimidate", "DSH"],
    ["background57", "Former Gladiator", "Campaign", "Scales of War", "It takes four failed death saves to kill you.", "Dra366"],
    ["background415", "Fortune Teller", "Racial", "General", "Associated: Insight, Perception", "PHR:T"],
    ["background187", "Found Religion Among Others", "Divine", "General", "Associated: Diplomacy, a skill another race gains a bonus to", "DP"],
    ["background314", "Found in the Wild", "Birth", "General", "Associated: Heal, Streetwise", "PP"],
    ["background578", "Founder", "Occupation", "General", "Associated: Athletics, History", "Dra387"],
    ["background171", "Foundling", "", "General", "Associated: Streetwise", "Dra374"],
    ["background329", "Free Spirit", "Racial", "General", "Associated: Athletics, Nature", "PP"],
    ["background540", "Freed Slave", "Occupation", "General", "Associated: Athletics, Endurance", "Dra386"],
    ["background499", "Freedom's Call", "Racial", "Dark Sun", "Associated: Endurance, Intimidate", "DSCS"],
    ["background566", "Friend of an Eladrin House", "Occupation", "General", "Associated: Arcana, Diplomacy, Elven", "Dra387"],
    ["background552", "Frog Hunter", "Racial", "General", "Associated: Perception, Stealth", "Dra386"],
    ["background304", "Frostfell (Primal Power)", "Geography", "General", "Associated: Athletics, Endurance, Dwarven", "PP"],
    ["background65", "Fugitive from a Vengeful Rival", "Campaign", "Scales of War", "Add Bluff and Stealth to class skill, and +1 to Bluff and Stealth.", "Dra366"],
    ["background406", "Gang Leader", "Racial", "General", "Associated: Stealth, Streetwise", "PHR:T"],
    ["background119", "Genasi - Academic Exhibit", "Racial", "General", "Associated: Arcana, Thievery", "PHB2"],
    ["background118", "Genasi - Chaos Burn", "Racial", "General", "Associated: Arcana, Endurance", "PHB2"],
    ["background80", "Geography - Desert", "Geography", "General", "Associated: Endurance, Nature", "PHB2"],
    ["background81", "Geography - Forest", "Geography", "General", "Associated: Nature, Perception", "PHB2"],
    ["background82", "Geography - Mountains", "Geography", "General", "Associated: Athletics, Dungeoneering", "PHB2"],
    ["background83", "Geography - Urban", "Geography", "General", "Associated: History, Streetwise", "PHB2"],
    ["background84", "Geography - Wetlands", "Geography", "General", "Associated: Athletics, Nature", "PHB2"],
    ["background202", "Ghallanda Dawn-Builder", "House Ghallanda", "Eberron", "Associated: Diplomacy, History", "EPG"],
    ["background201", "Ghallanda Enclave Guard", "House Ghallanda", "Eberron", "Associated: Perception, Insight", "EPG"],
    ["background208", "Ghorad'din Recruit", "House Kundarak", "Eberron", "Associated: Bluff, Stealth", "EPG"],
    ["background714", "Ghost of Nerath", "Occupation", "General", "Associated: Endurance, History", "Dra391"],
    ["background269", "Githzerai - Cenobite Initiate", "Racial", "General", "Associated: Arcana, History", "PHB3"],
    ["background270", "Githzerai - War Band Survivor", "Racial", "General", "Associated: Dungeoneering, Perception", "PHB3"],
    ["background722", "Gladiator - Follower of Kord", "Gladiator", "General", "Associated: Athletics, Endurance", "Dra392"],
    ["background351", "Glamoured (Fey)", "", "General", "Associated: Nature, Stealth", "Dra381"],
    ["background367", "Gloaming Guardian", "Racial", "General", "Associated: Intimidate, Stealth", "Dra382"],
    ["background142", "Gnome - Estranged Fey", "Racial", "General", "Associated: Endurance, Nature", "PHB2"],
    ["background120", "Gnome - Fomorian Captivity", "Racial", "General", "Associated: Endurance, Stealth", "PHB2"],
    ["background573", "Goblin Foe", "", "General", "Associated: Intimidate, Perception, Goblin", "HS1"],
    ["background711", "God Hater", "", "General", "Associated: Intimidate, Primordial", "Dra390"],
    ["background786", "Gold Dwarf", "Racial", "Neverwinter", "Associated: Dungeoneering, Deep Speech, Elven", "NCS"],
    ["background123", "Goliath - Lightlost", "Racial", "General", "Associated: Athletics, Dungeoneering", "PHB2"],
    ["background122", "Goliath - Skywatcher", "Racial", "General", "Associated: History, Religion", "PHB2"],
    ["background332", "Grave Digger", "Occupation", "General", "Associated: Athletics, Endurance", "Dra380"],
    ["background14", "Gray Vale", "Campaign", "Faerûn", "Gain one language, add Nature to class skill, and +2 to Nature.", "FRPG"],
    ["background15", "Great Dale", "Campaign", "Faerûn", "Add Arcana and Nature to class skill, and +1 to Arcana and Nature.", "FRPG"],
    ["background837", "Green Moss Guide", "Racial", "", "Associated: Acrobatics, Nature", "Dra429"],
    ["background362", "Grifter", "Occupation", "General", "Associated: Bluff, Insight", "Dra381"],
    ["background49", "Gritty Sergeant", "Campaign", "Scales of War", "Gain proficiency in a simple or military weapon, and +1 to initiative.", "Dra366"],
    ["background524", "Guardian Contemplative", "Racial", "General", "Associated: Arcana, Religion", "Dra385"],
    ["background525", "Guardian Sentinel", "Racial", "General", "Associated: Intimidate, Perception", "Dra385"],
    ["background761", "Guide", "Occupation", "General", "Associated: Nature, Perception, Elven", "Dra394"],
    ["background670", "Guiding Hand", "", "General", "Associated: Diplomacy, Perception", "PsP"],
    ["background634", "Gulg - Enlightened Seer", "Geography", "Dark Sun", "Associated: Insight, Stealth", "DSCS"],
    ["background636", "Gulg - Judaga", "Geography", "Dark Sun", "Associated: Insight, Stealth", "DSCS"],
    ["background635", "Gulg - Paper Wasp", "Geography", "Dark Sun", "Associated: Insight, Stealth", "DSCS"],
    ["background821", "Halaster's Clone", "", "Faerûn", "Associated: Arcana, Insight", "Dra409"],
    ["background770", "Half-Elemental Refugee", "Campaign", "Dark Sun", "Associated: Perception, Stealth", "Dra396"],
    ["background125", "Half-Elf - Cultural Half-Elf", "Racial", "General", "Associated: History", "PHB2"],
    ["background141", "Half-Elf - Outcast", "Racial", "General", "Associated: Endurance, Nature", "PHB2"],
    ["background124", "Half-Elf - Wanderer", "Racial", "General", "Associated: Streetwise", "PHB2"],
    ["background513", "Half-Giant Laborer", "Racial", "Dark Sun", "Associated: Athletics, Endurance", "DSCS"],
    ["background128", "Half-Orc - First Generation", "Racial", "General", "Associated: Bluff", "PHB2"],
    ["background126", "Half-Orc - Orc Birth", "Racial", "General", "Associated: Athletics", "PHB2"],
    ["background127", "Half-Orc - Stormtouched", "Racial", "General", "Associated: Nature, Religion", "PHB2"],
    ["background130", "Halfling - Avandra's Kiss", "Racial", "General", "Associated: Acrobatics, Heal", "PHB2"],
    ["background131", "Halfling - Banned", "Racial", "General", "Associated: Bluff, Stealth", "PHB2"],
    ["background357", "Halfling - High Roller", "Racial", "General", "Associated: Bluff, Streetwise", "Dra381"],
    ["background358", "Halfling - River Scout", "Racial", "General", "Associated: Athletics, Nature", "Dra381"],
    ["background129", "Halfling - Storyteller", "Racial", "General", "Associated: History, Religion", "PHB2"],
    ["background279", "Hand-For-Hire", "Adventurers", "Faerûn", "Associated: Heal, Thievery", "Dra376"],
    ["background776", "Harper Agent", "Campaign", "Neverwinter", "Associated: Bluff, Insight", "NCS"],
    ["background508", "Haunted Survivor", "Racial", "Dark Sun", "Associated: Endurance, Nature", "DSCS"],
    ["background58", "Haunted Veteran", "Campaign", "Scales of War", "Once per encounter, reroll a failed saving throw against a fear effect.", "Dra366"],
    ["background517", "Heartless Mercenary", "Racial", "Dark Sun", "Associated: Acrobatics, Stealth", "DSCS"],
    ["background403", "Heaven's Weapon", "Racial", "General", "Associated: History, Religion, Supernal", "PHR:T"],
    ["background780", "Heir of Delzoun", "Campaign", "Neverwinter", "Associated: Dungeoneering, History", "NCS"],
    ["background696", "Heir to Power", "Racial", "General", "Associated: Arcana, Religion", "PsP"],
    ["background400", "Hellfire Heir", "Racial", "General", "Associated: Arcana, Religion, Supernal", "PHR:T"],
    ["background470", "Hellion", "Society", "General", "Associated: Acrobatics, Athletics", "MP2"],
    ["background686", "Hereditary Psionics User", "Racial", "General", "Associated: History, Intimidate", "PsP"],
    ["background188", "Heretic", "Divine", "General", "Associated: History, Stealth", "DP"],
    ["background16", "High Imaskar", "Campaign", "Faerûn", "Can reroll any Arcana.", "FRPG"],
    ["background274", "High Roller", "Adventurers", "Faerûn", "Associated: Bluff, Streetwise", "Dra376"],
    ["background553", "Histachii", "Racial", "General", "Associated: Arcana, Insight, Draconic", "Dra386"],
    ["background562", "Holy Killer", "Occupation", "General", "Associated: Diplomacy, Insight", "Dra386"],
    ["background394", "House of Lies", "Racial", "General", "Associated: Bluff, History", "PHR:T"],
    ["background305", "Howling Plains", "Geography", "General", "Associated: Athletics, Endurance, Goblin", "PP"],
    ["background703", "Hulking", "Racial", "General", "Associated: Endurance, Intimidate", "PsP"],
    ["background132", "Human - Ancestral Holdings", "Racial", "General", "Associated: Diplomacy, History", "PHB2"],
    ["background133", "Human - Heir of the Forgotten Gods", "Racial", "General", "Associated: Insight, Religion", "PHB2"],
    ["background519", "Hunter", "Racial", "Dark Sun", "Associated: Endurance, Intimidate", "DSCS"],
    ["background523", "Ikemmu", "Geography", "General", "+2 to Arcana and Dungeoneering in addition to a +2 to skill when using any travel ritual.", "Dun175"],
    ["background778", "Iliyanbruen Guardian", "Campaign", "Neverwinter", "Associated: Arcana, Nature", "NCS"],
    ["background77", "Imbuer", "Campaign", "Scales of War", "Can construct implements and wondrous items. Can cast Creation rituals as if you have Ritual Caster.", "Dra366"],
    ["background17", "Impiltur", "Campaign", "Faerûn", "Add the higher of Wisdom score or Constitution score to starting hit points.", "FRPG"],
    ["background534", "Incomplete Creation", "Racial", "General", "Associated: Arcana, Endurance", "Dra385"],
    ["background172", "Indulged Scion", "", "General", "Associated: Bluff, Intimidate", "Dra374"],
    ["background810", "Infernal Slave", "", "General", "Associated: Bluff, Insight", "The Book of Vile Darkness"],
    ["background732", "Initiate of al-Shaphal", "", "General", "Associated: Insight, Religion", "Dra392"],
    ["background262", "Inquisitive", "Occupation", "Eberron", "Associated: Insight, Streetwise", "EPG"],
    ["background173", "Instructor's Child", "", "General", "Associated: Insight", "Dra374"],
    ["background824", "Inverness Survivor", "", "General", "Associated: Arcana, Nature, Religion", "DSH"],
    ["background207", "Iron Gatekeeper", "House Kundarak", "Eberron", "Associated: Arcana, Thievery", "EPG"],
    ["background688", "Iron Mind", "Racial", "General", "Associated: Insight, Intimidate", "PsP"],
    ["background313", "Isolated", "Society", "General", "Associated: Endurance, Nature", "PP"],
    ["background674", "Isolated (Psionic)", "Society", "General", "Associated: Arcana, History", "PsP"],
    ["background637", "Ivory Triangle - Beleaguered Sentry", "Geography", "Dark Sun", "Associated: Endurance, Perception, Deep Speech", "DSCS"],
    ["background638", "Ivory Triangle - Driven Bounty Hunter", "Geography", "Dark Sun", "Associated: Endurance, Perception, Deep Speech", "DSCS"],
    ["background639", "Ivory Triangle - Hardened Traveler", "Geography", "Dark Sun", "Associated: Endurance, Perception, Deep Speech", "DSCS"],
    ["background640", "Ivory Triangle - Wanted in the Seven Cities", "Geography", "Dark Sun", "Associated: Endurance, Perception, Deep Speech", "DSCS"],
    ["background205", "Jorasco Investigator", "House Jorasco", "Eberron", "Associated: Heal, Insight", "EPG"],
    ["background204", "Jorasco Medic", "House Jorasco", "Eberron", "Associated: Heal", "EPG"],
    ["background836", "Kapak Draconian", "Racial", "", "Associated: Intimidate, Stealth, Thievery", "Dra421"],
    ["background237", "Karrnath", "Geography", "Eberron", "Associated: Athletics, Intimidate", "EPG"],
    ["background704", "Keen Senses", "Racial", "General", "Associated: Perception", "PsP"],
    ["background417", "Keeper of Hate", "Racial", "General", "Associated: Arcana, Intimidate", "Dra383"],
    ["background738", "Keeper of the Flame", "Society", "General", "Associated: Arcana, Religion", "Dra393"],
    ["background667", "Keepers of the Internal Sun", "", "General", "Associated: History, Perception, Draconic", "PsP"],
    ["background254", "Khyber", "Geography", "Eberron", "Associated: Dungeoneering, Endurance", "EPG"],
    ["background706", "Knife Enthusiast", "Occupation", "General", "Associated: Bluff, Insight", "Dra390"],
    ["background833", "Knowledge Hunter", "Racial", "General", "Associated: Arcana, Dungeoneering", "Dra411"],
    ["background768", "Kord Clan", "Origin", "General", "Associated: Athletics, Intimidate", "Dra395"],
    ["background209", "Korunda Vault-Keeper", "House Kundarak", "Eberron", "Associated: Dungeoneering, History", "EPG"],
    ["background739", "Last Legionnaire", "Society", "General", "Associated: Endurance, Heal", "Dra393"],
    ["background63", "Last of the Breed", "Campaign", "Scales of War", "Add Endurance and Perception to class skill, and +1 to Endurance and Perception.", "Dra366"],
    ["background501", "Last of the Clutch", "Racial", "Dark Sun", "Associated: Endurance, Insight", "DSCS"],
    ["background395", "Last of the Line", "Racial", "General", "Associated: Diplomacy, History", "PHR:T"],
    ["background372", "Laudable Legacy", "Racial", "General", "Associated: History, Diplomacy", "PHR:D"],
    ["background576", "Lawmaker", "Occupation", "General", "Associated: Diplomacy, History", "Dra387"],
    ["background244", "Lhazaar Principalities", "Geography", "Eberron", "Associated: Athletics, Thievery", "EPG"],
    ["background224", "Liondrake's Roar Mercenary", "House Tharashk", "Eberron", "Associated: Nature, Dungeoneering", "EPG"],
    ["background819", "Llewyrr Elf", "Racial", "General", "Associated: Arcana, History, Insight, Nature", "Dra405"],
    ["background828", "Longbridge Local", "", "General", "Associated: Arcana, History", "DSH"],
    ["background716", "Lost Drifter", "Racial", "General", "Associated: Nature, Perception", "Dra391"],
    ["background166", "Lost Kin", "Legacy of Acererak", "General", "Associated: Any skill, Any language except Abyssal or Supernal. +3 bonus to Natural checks made to recall geography.", "Dra371"],
    ["background536", "Lost Love", "Occupation", "General", "Associated: Diplomacy, Insight", "Dra386"],
    ["background586", "Lucky Child", "", "General", "Associated: Insight, Religion", "Dra388"],
    ["background18", "Luruar", "Campaign", "Faerûn", "Can reroll any History.", "FRPG"],
    ["background752", "Luruar (Shifter)", "Campaign", "Faerûn", "Add Chondathan to languages known, add Intimidate to class skills, and +2 to Perception while shifting.", "Dra394"],
    ["background19", "Luskan", "Campaign", "Faerûn", "Add Stealth and Thievery to class skill, and +1 to Stealth and Thievery.", "FRPG"],
    ["background753", "Luskan (Shifter)", "Campaign", "Faerûn", "Reroll any Stealth. Add Shou to known languages.", "Dra394"],
    ["background210", "Lyrandar Airship Sailor", "House Lyrandar", "Eberron", "Associated: Athletics, Perception", "EPG"],
    ["background212", "Lyrandar Privateer", "House Lyrandar", "Eberron", "Associated: Acrobatics, Athletics", "EPG"],
    ["background211", "Lyrandar Raincaller", "House Lyrandar", "Eberron", "Associated: Athletics, Nature", "EPG"],
    ["background391", "Mad Wanderer", "Campaign", "Eberron", "Associated: Bluff, Stealth", "Dra382"],
    ["background306", "Maelstrom", "Geography", "General", "Associated: Athletics, Intimidate, Primordial", "PP"],
    ["background37", "Magic Scholar", "Campaign", "Scales of War", "Add Arcana and History to class skill, and +1 to Arcana and History.", "Dra366"],
    ["background568", "Magpie", "Racial", "General", "Associated: Perception, Streetwise", "Dra387"],
    ["background510", "Market Thief", "Racial", "Dark Sun", "Associated: Streetwise, Thievery", "DSCS"],
    ["background200", "Marshal's Deputy", "House Deneith", "Eberron", "Associated: Intimidate, Streetwise", "EPG"],
    ["background459", "Martial - Bearer of the Heirloom", "Martial", "General", "Associated: History, Intimidate", "MP2"],
    ["background460", "Martial - Disenchanted", "Martial", "General", "Associated: Arcana, Endurance", "MP2"],
    ["background461", "Martial - Garrison Child", "Martial", "General", "Associated: Athletics, History", "MP2"],
    ["background462", "Martial - Guild Orphan", "Martial", "General", "Associated: Perception, Thievery", "MP2"],
    ["background463", "Martial - Local Hero", "Martial", "General", "Associated: Diplomacy, Nature", "MP2"],
    ["background464", "Martial - Scion of a Legend", "Martial", "General", "Associated: Bluff, Intimidate", "MP2"],
    ["background822", "Masked Lord", "", "Faerûn", "Associated: Diplomacy, History", "Dra409"],
    ["background414", "Memory Seeker", "Racial", "General", "Associated: Dungeoneering, History", "PHR:T"],
    ["background266", "Mental Bastion", "Racial", "Eberron", "Associated: Arcana, Insight", "EPG"],
    ["background834", "Merchant Hunter", "Racial", "General", "Associated: Diplomacy, Insight", "Dra411"],
    ["background42", "Merchant Prince", "Campaign", "Scales of War", "Learn an extra language, add Insight to class skill, and +2 to Insight.", "Dra366"],
    ["background717", "Merciless Brigand", "Racial", "General", "Associated: Intimidate, Stealth", "Dra391"],
    ["background475", "Minotaur - Baphomet Clan Exile", "Racial", "General", "Associated: Religion, Stealth", "PHB3"],
    ["background476", "Minotaur - Silenced Beast", "Racial", "General", "Associated: Diplomacy, Insight", "PHB3"],
    ["background684", "Mirror Mind", "Racial", "General", "Associated: Bluff, Insight", "PsP"],
    ["background76", "Missing Master", "Campaign", "Scales of War", "Add Perception and Insight to class skill, and +1 to Perception and Insight.", "Dra366"],
    ["background189", "Missionary Life", "Divine", "General", "Associated: Endurance, Nature", "DP"],
    ["background258", "Mist-Touched", "Adulthood", "Eberron", "Associated: Endurance, Intimidate", "EPG"],
    ["background675", "Monastic", "Society", "General", "Associated: Athletics, Religion", "PsP"],
    ["background487", "Monastic (Avandra)", "Occupation", "General", "Associated: Dungeoneering, Nature", "Dra384"],
    ["background488", "Monastic (Bahamut)", "Occupation", "General", "Associated: Insight, Intimidate", "Dra384"],
    ["background489", "Monastic (Corellon)", "Occupation", "General", "Associated: Arcana, Insight", "Dra384"],
    ["background490", "Monastic (Erathis)", "Occupation", "General", "Associated: Diplomacy, Streetwise", "Dra384"],
    ["background491", "Monastic (Ioun)", "Occupation", "General", "Associated: History, Insight", "Dra384"],
    ["background492", "Monastic (Kord)", "Occupation", "General", "Associated: Athletics, Endurance", "Dra384"],
    ["background493", "Monastic (Melora)", "Occupation", "General", "Associated: Nature, Perception", "Dra384"],
    ["background494", "Monastic (Moradin)", "Occupation", "General", "Associated: Endurance, History", "Dra384"],
    ["background495", "Monastic (Pelor)", "Occupation", "General", "Associated: Diplomacy, Heal", "Dra384"],
    ["background496", "Monastic (Raven Queen)", "Occupation", "General", "Associated: Intimidate, Religion", "Dra384"],
    ["background497", "Monastic (Sehanine)", "Occupation", "General", "Associated: Perception, Stealth", "Dra384"],
    ["background64", "Monster Hunter", "Campaign", "Scales of War", "+2 whenever use a knowledge skill to make a monster knowledge.", "Dra366"],
    ["background788", "Moon Elf", "Racial", "Neverwinter", "Associated: Diplomacy, Streetwise, Chondathan, Damaran, Untheric", "NCS"],
    ["background20", "Moonshae Isles", "Campaign", "Faerûn", "Know Elven as an language, and +2 to saves against charm and fear effects.", "FRPG"],
    ["background754", "Moonshae Isles (Shifter)", "Campaign", "Faerûn", "Add Athletics to class skill. +3 bonus to Athletics checks made to swim, piloting water vessels, or move on boat. Add Chondathan to known languages.", "Dra394"],
    ["background365", "Moonstruck Hunter", "", "General", "Associated: Perception, Stealth", "Dra382"],
    ["background238", "Mournland (Cyre)", "Geography", "Eberron", "Associated: Endurance,Streetwise", "EPG"],
    ["background245", "Mror Holds", "Geography", "Eberron", "Associated: Dungeoneering, Endurance", "EPG"],
    ["background363", "Muscle", "Occupation", "General", "Associated: Athletics, Intimidate", "Dra381"],
    ["background830", "Myth Drannor", "Campaign", "Encounters", "Associated: Arcana, Nature", "Web of the Spider Queen"],
    ["background21", "Myth Drannor (FRPG)", "Campaign", "Faerûn", "Once per encounter, can reroll a failed saving throw against a charm effect.", "FRPG"],
    ["background529", "Mythspeaker", "Racial", "General", "Associated: Diplomacy, History, Quori", "Dra385"],
    ["background352", "Naive Arrogance", "", "General", "Associated: Arcana, Bluff", "Dra381"],
    ["background22", "Narfell", "Campaign", "Faerûn", "Add Endurance to class skill, and +3 to Endurance.", "FRPG"],
    ["background599", "Narrow Way Clan", "Racial", "General", "Associated: History, Religion", "Dra389"],
    ["background725", "Natural - Follower of Kord", "Natural", "General", "Associated: Insight, Streetwise", "Dra392"],
    ["background264", "Natural Chameleon", "Racial", "Eberron", "Associated: Bluff, Stealth", "EPG"],
    ["background518", "Nature's Protector", "Racial", "Dark Sun", "Associated: Heal, Nature", "DSCS"],
    ["background167", "Necromancer's Chattel", "Legacy of Acererak", "General", "Associated: Endurance, Religion, Stealth. +2 to save against fear effects.", "Dra371"],
    ["background23", "Nelanther Isles", "Campaign", "Faerûn", "Add Acrobatics and Athletics to class skill, and +1 to Acrobatics and Athletics.", "FRPG"],
    ["background24", "Netheril", "Campaign", "Faerûn", "Add Arcana and History to class skill, and +1 to Arcana and History.", "FRPG"],
    ["background774", "Neverwinter Noble", "Campaign", "Neverwinter", "Associated: Diplomacy, History", "NCS"],
    ["background641", "Nibenay - Gifted Dancer", "Geography", "Dark Sun", "Associated: Acrobatics, Insight", "DSCS"],
    ["background642", "Nibenay - Walker of the Exalted Path", "Geography", "Dark Sun", "Associated: Acrobatics, Insight", "DSCS"],
    ["background763", "Nightmares of Defiling", "Campaign", "Dark Sun", "Associated: Intimidate, Nature", "Dra395"],
    ["background73", "Noble Bred for War", "Campaign", "Scales of War", "Gain proficiency in a simple or military weapon, and +1 to Diplomacy.", "Dra366"],
    ["background50", "Noble Scion", "Campaign", "Scales of War", "Add a knowledge skill to class skill, and +2 to with that skill.", "Dra366"],
    ["background514", "Noble's Guard", "Racial", "Dark Sun", "Associated: Intimidate, Streetwise", "DSCS"],
    ["background590", "Oathbound Death-Seeker", "Racial", "General", "Associated: Endurance, Intimidate", "Dra388"],
    ["background174", "Oathbound Fellow", "", "General", "Associated: Bluff, Insight", "Dra374"],
    ["background94", "Occupation - Artisan", "Occupation", "General", "Associated: Athletics, Diplomacy", "PHB2"],
    ["background143", "Occupation - Bounty Hunter", "Occupation", "General", "Associated: Perception, Stealth, Any language except Abyssal or Supernal", "Dra373"],
    ["background95", "Occupation - Criminal", "Occupation", "General", "Associated: Stealth, Thievery", "PHB2"],
    ["background96", "Occupation - Entertainer", "Occupation", "General", "Associated: Bluff, History", "PHB2"],
    ["background144", "Occupation - Executioner", "Occupation", "General", "Associated: Bluff, Intimidate", "Dra373"],
    ["background97", "Occupation - Farmer", "Occupation", "General", "Associated: Endurance, Nature", "PHB2"],
    ["background145", "Occupation - Foe Killer", "Occupation", "General", "Associated: Insight, Perception, or the knowledge skill that best relates to your enemy, The language commonly spoken by your enemy", "Dra373"],
    ["background146", "Occupation - Guerrilla", "Occupation", "General", "Associated: Perception, Stealth", "Dra373"],
    ["background147", "Occupation - Hired Killer", "Occupation", "General", "Associated: Athletics, Stealth, Secret Language", "Dra373"],
    ["background148", "Occupation - Hunter", "Occupation", "General", "Associated: Nature, Perception, Stealth", "Dra373"],
    ["background149", "Occupation - Infiltrator", "Occupation", "General", "Associated: Bluff, Stealth, Any language except Abyssal or Supernal", "Dra373"],
    ["background98", "Occupation - Mariner", "Occupation", "General", "Associated: Acrobatics, Perception", "PHB2"],
    ["background157", "Occupation - Merchant", "Occupation", "General", "Associated: Bluff, Diplomacy", "PHB2"],
    ["background99", "Occupation - Military", "Occupation", "General", "Associated: Athletics, Endurance", "PHB2"],
    ["background150", "Occupation - Mystic Slayer", "Occupation", "General", "Associated: Arcana, Stealth, Draconic", "Dra373"],
    ["background151", "Occupation - Poison Master", "Occupation", "General", "Associated: Nature, Thievery", "Dra373"],
    ["background152", "Occupation - Punisher", "Occupation", "General", "Associated: Intimidate, Streetwise", "Dra373"],
    ["background153", "Occupation - Revolutionary", "Occupation", "General", "Associated: History, Streetwise", "Dra373"],
    ["background100", "Occupation - Scholar", "Occupation", "General", "Associated: Arcana, Religion", "PHB2"],
    ["background154", "Occupation - Thief", "Occupation", "General", "Associated: Stealth, Thievery, Secret Language", "Dra373"],
    ["background155", "Occupation - Thug", "Occupation", "General", "Associated: Athletics, Intimidate, Secret Language", "Dra373"],
    ["background156", "Occupation - Zealous Slayer", "Occupation", "General", "Associated: Endurance, Religion", "Dra373"],
    ["background74", "Officer Who Came Out of Retirement", "Campaign", "Scales of War", "+1 to initiative, add History to class skill, and +1 to History.", "Dra366"],
    ["background775", "Oghma's Faithful", "Campaign", "Neverwinter", "Associated: History, Religion, Streetwise", "NCS"],
    ["background69", "On the Run from the Devil", "Campaign", "Scales of War", "Add Bluff and Perception to class skill, and +1 to Bluff and Perception.", "Dra366"],
    ["background418", "Orc Slayer", "Racial", "General", "Associated: Intimidate, Nature", "Dra383"],
    ["background547", "Order of the Golden Cup", "Geography", "Faerûn", "Associated: Heal, Insight", "Dun177"],
    ["background215", "Orien Courier", "House Orien", "Eberron", "Associated: Acrobatics, Stealth", "EPG"],
    ["background216", "Orien Smuggler", "House Orien", "Eberron", "Associated: Acrobatics, Stealth", "EPG"],
    ["background758", "Orphan of the Gibbering Massacre", "Origin", "General", "Associated: Dungeoneering, Insight, Deep Speech", "Dra394"],
    ["background676", "Ostracized", "Society", "General", "Associated: Intimidate, Stealth", "PsP"],
    ["background190", "Out for Revenge", "Divine", "General", "Associated: Endurance, Intimidate", "DP"],
    ["background793", "Pack Outcast", "Campaign", "Neverwinter", "Associated: Nature, Perception", "NCS"],
    ["background341", "Pact", "Racial", "General", "Associated: History, Religion", "Dra380"],
    ["background559", "Padding Wolf", "Racial", "General", "Associated: Perception, Stealth, Giant", "Dra386"],
    ["background687", "Paranoid Manipulator", "Racial", "General", "Associated: Bluff, Perception", "PsP"],
    ["background424", "Parentage - Cult Raised", "Birth", "General", "Associated: History, Religion, Abyssal", "Dra383"],
    ["background423", "Parentage - Draconic Adoption", "Birth", "General", "Associated: Arcana, Draconic", "Dra383"],
    ["background421", "Parentage - Ill-Omened", "Birth", "General", "Associated: Arcana, Religion", "Dra383"],
    ["background428", "Parentage - Immortal Guardians", "Birth", "General", "Associated: Arcana, Religion", "Dra383"],
    ["background419", "Parentage - Impoverished", "Birth", "General", "Associated: Endurance, Streetwise", "Dra383"],
    ["background426", "Parentage - Minstrel Family", "Birth", "General", "Associated: Acrobatics, Diplomacy", "Dra383"],
    ["background425", "Parentage - Monk Business", "Birth", "General", "Associated: Heal, History", "Dra383"],
    ["background422", "Parentage - Noble", "Birth", "General", "Associated: Diplomacy, Perception", "Dra383"],
    ["background420", "Parentage - Orphan", "Birth", "General", "Associated: Bluff, Insight", "Dra383"],
    ["background427", "Parentage - Raised by Wolves", "Birth", "General", "Associated: Intimidate, Nature", "Dra383"],
    ["background191", "Penitent", "Divine", "General", "Associated: Stealth, Thievery", "DP"],
    ["background740", "People of the Gold Dragon", "Society", "General", "Associated: Diplomacy, Nature", "Dra393"],
    ["background615", "Perfect Recollection", "Racial", "General", "Associated: History, Intimidate", "Dra389"],
    ["background538", "Persecuted", "Occupation", "General", "Associated: Bluff, Perception", "Dra386"],
    ["background219", "Phiarlan Archivist", "House Phiarlan", "Eberron", "Associated: Arcana, History", "EPG"],
    ["background446", "Pivotal Event - Amazing Creation", "Pivotal Event", "General", "Associated: Arcana, Stealth", "Dra383"],
    ["background444", "Pivotal Event - Divine Decree", "Pivotal Event", "General", "Associated: Religion, Nature", "Dra383"],
    ["background443", "Pivotal Event - Escape", "Pivotal Event", "General", "Associated: Athletics, Stealth", "Dra383"],
    ["background440", "Pivotal Event - Murder", "Pivotal Event", "General", "Associated: Perception", "Dra383"],
    ["background445", "Pivotal Event - Portal Mishap", "Pivotal Event", "General", "Associated: Diplomacy, History", "Dra383"],
    ["background448", "Pivotal Event - Possession", "Pivotal Event", "General", "Associated: Arcana, Abyssal", "Dra383"],
    ["background447", "Pivotal Event - Transformation", "Pivotal Event", "General", "Associated: Insight, Intimidate", "Dra383"],
    ["background442", "Pivotal Event - Unwholesome Journey", "Pivotal Event", "General", "Associated: Dungeoneering, Deep Speech", "Dra383"],
    ["background441", "Pivotal Event - You Die", "Pivotal Event", "General", "Associated: Endurance, Heal", "Dra383"],
    ["background439", "Pivotal Event - You Kill", "Pivotal Event", "General", "Associated: Bluff, Heal", "Dra383"],
    ["background539", "Pledged Scout", "Occupation", "General", "Associated: Nature, Perception", "Dra386"],
    ["background68", "Political Rebel", "Campaign", "Scales of War", "Add Diplomacy and Streetwise to class skill, and +1 to Diplomacy and Streetwise.", "Dra366"],
    ["background326", "Primal Fey", "Racial", "General", "Associated: Arcana, Nature", "PP"],
    ["background315", "Primal Omen", "Birth", "General", "Associated: Arcana, Nature", "PP"],
    ["background327", "Primal Soul", "Racial", "General", "Associated: Athletics, Nature", "PP"],
    ["background60", "Prison Conversion", "Campaign", "Scales of War", "Add Streetwise to class skill, and +3 to Streetwise.", "Dra366"],
    ["background220", "Prophecy Sage", "House Sivis", "Eberron", "Associated: Arcana,Diplomacy", "EPG"],
    ["background399", "Prophesied Master", "Racial", "General", "Associated: Insight, Perception", "PHR:T"],
    ["background560", "Prophetic Sanctification", "Occupation", "General", "Associated: Insight, Perception", "Dra386"],
    ["background565", "Protégé of the Circle", "Occupation", "General", "Associated: History, Insight", "Dra387"],
    ["background741", "Provincial Renegade", "Society", "General", "Associated: Intimidate, Streetwise", "Dra393"],
    ["background616", "Psiforged", "Racial", "General", "Associated: Arcana, Insight", "Dra389"],
    ["background413", "Psionic Academy Dropout", "Racial", "General", "Associated: Arcana, Intimidate", "PHR:T"],
    ["background697", "Psionic Artifice", "Racial", "General", "Associated: Insight, Streetwise", "PsP"],
    ["background593", "Psionic Descendant", "Racial", "General", "Associated: Arcana, History", "Dra388"],
    ["background694", "Psychic Hunter", "Racial", "General", "Associated: Nature, Perception", "PsP"],
    ["background745", "Purified Soul", "Racial", "General", "Associated: Insight, Religion", "Dra393"],
    ["background246", "Q'barra", "Geography", "Eberron", "Associated: Endurance, Nature", "EPG"],
    ["background528", "Quori Nightmare", "Racial", "General", "Associated: Intimidate, Insight", "Dra385"],
    ["background643", "Raam - Badna Dedicate", "Geography", "Dark Sun", "Associated: Religion, Streetwise, Elven", "DSCS"],
    ["background644", "Raam - Dedicated Rebel", "Geography", "Dark Sun", "Associated: Religion, Streetwise, Elven", "DSCS"],
    ["background645", "Raam - Honest Mansabdar", "Geography", "Dark Sun", "Associated: Religion, Streetwise, Elven", "DSCS"],
    ["background542", "Racial Devotee", "Racial", "General", "Associated: History, Insight, A language the imitated race speaks", "Dra386"],
    ["background338", "Raised", "Psychology", "General", "Associated: Intimidate, Religion", "Dra380"],
    ["background543", "Raised as Another", "Racial", "General", "Associated: A skill to which the imitated race gains a bonus, A language the imitated race speaks", "Dra386"],
    ["background412", "Raised by Wild Beasts", "Racial", "General", "Associated: Nature, any skill in which your adoptive parent is trained, A language spoken by your adoptive parent", "PHR:T"],
    ["background483", "Raised in the Unseen Path", "", "General", "Associated: Arcana, Nature, Elven", "Dra384"],
    ["background755", "Rashemen (Shifter)", "Campaign", "Faerûn", "Add Damaran to languages known, add Nature to class skills, and +2 to Bluff, Diplomacy, and Insight when dealing with fey.", "Dra394"],
    ["background811", "Reaver", "", "General", "Associated: Endurance, Intimidate", "The Book of Vile Darkness"],
    ["background294", "Rebel", "Occupation", "General", "Associated: Endurance, Thievery", "Dra378"],
    ["background56", "Recent Convert", "Campaign", "Scales of War", "Once per encounter, reroll a failed saving throw against a charm effect.", "Dra366"],
    ["background458", "Recent Life - Demon-Hunter", "Recent Life", "General", "Associated: Arcana, Endurance", "Dra383"],
    ["background457", "Recent Life - Explorer of the Ancient", "Recent Life", "General", "Associated: Dungeoneering, History, Thievery", "Dra383"],
    ["background451", "Recent Life - Fighting Undead", "Recent Life", "General", "Associated: Religion", "Dra383"],
    ["background452", "Recent Life - Freeing Slaves", "Recent Life", "General", "Associated: Diplomacy, Thievery", "Dra383"],
    ["background450", "Recent Life - Lost in the Feywild", "Recent Life", "General", "Associated: Nature, Elven", "Dra383"],
    ["background453", "Recent Life - Mercenary Work", "Recent Life", "General", "Associated: Athletics, Endurance", "Dra383"],
    ["background455", "Recent Life - Peaceful Life", "Recent Life", "General", "Associated: Athletics, Insight", "Dra383"],
    ["background454", "Recent Life - Spreading the Word", "Recent Life", "General", "Associated: History, Religion", "Dra383"],
    ["background449", "Recent Life - Teambuilding Exercise", "Recent Life", "General", "Associated: Diplomacy, Streetwise", "Dra383"],
    ["background456", "Recent Life - Valued Prisoner", "Recent Life", "General", "Associated: Streetwise, Thievery", "Dra383"],
    ["background771", "Reclaimed Birthright", "Campaign", "Dark Sun", "Associated: History, Intimidate", "Dra396"],
    ["background605", "Reclusive Mystic", "Racial", "General", "Associated: Endurance, Nature", "Dra389"],
    ["background742", "Red Pilgrim", "Society", "General", "Associated: Perception, Stealth", "Dra393"],
    ["background574", "Redeemer of the Desecrated", "", "General", "Associated: Dungeoneering, Religion", "HS1"],
    ["background295", "Redemption", "Occupation", "General", "Associated: Arcana, Bluff", "Dra378"],
    ["background31", "Redemption Seeker", "Campaign", "Scales of War", "Add Diplomacy and Insight to class skill, and +1 to Diplomacy and Insight.", "Dra366"],
    ["background580", "Reformed Villain", "", "General", "Associated: Giant, Goblin, Primordial", "Dra387"],
    ["background720", "Refugee", "Racial", "General", "Associated: Endurance, Stealth", "Dra392"],
    ["background259", "Refugee (Eberron Player's Guide)", "Adulthood", "Eberron", "Associated: Endurance, Streetwise", "EPG"],
    ["background317", "Refugee (Primal Power)", "Birth", "General", "Associated: Intimidate, Thievery", "PP"],
    ["background175", "Refused Admittance", "", "General", "Associated: Perception", "Dra374"],
    ["background404", "Rejected Inheritance", "Racial", "General", "Associated: Bluff, Stealth", "PHR:T"],
    ["background381", "Reluctant Pawn of Tiamat", "Racial", "General", "Associated: Bluff, Thievery", "PHR:D"],
    ["background353", "Remnant Legacy (Vestige)", "", "General", "Associated: Arcana, History", "Dra381"],
    ["background318", "Renegade", "Occupation", "General", "Associated: Arcana, Streetwise", "PP"],
    ["background520", "Renegade Mercenary", "Racial", "Dark Sun", "Associated: Perception, Stealth", "DSCS"],
    ["background781", "Renegade Red Wizard", "Campaign", "Neverwinter", "Associated: Bluff, Heal, Religion, Stealth", "NCS"],
    ["background168", "Restless Dead", "Legacy of Acererak", "General", "Associated: Insight, Perception, Religion. +1 to damage rolls against undead.", "Dra371"],
    ["background712", "Resurrectionist", "", "General", "Associated: Diplomacy, Heal", "Dra390"],
    ["background319", "Revered Elder", "Occupation", "General", "Associated: Insight, Nature", "PP"],
    ["background646", "Ringing Mountains - Isolated Monastery", "Geography", "Dark Sun", "Associated: Athletics, Nature", "DSCS"],
    ["background647", "Ringing Mountains - Mountain Tribe", "Geography", "Dark Sun", "Associated: Athletics, Nature", "DSCS"],
    ["background648", "Ringing Mountains - Prospector", "Geography", "Dark Sun", "Associated: Athletics, Nature", "DSCS"],
    ["background592", "River Guardian", "Racial", "General", "Associated: Acrobatics, Perception", "Dra388"],
    ["background47", "River Smuggler", "Campaign", "Scales of War", "Add Athletics and Streetwise to class skill, and +1 to Athletics and Streetwise.", "Dra366"],
    ["background649", "Road of Kings - Druid Initiate", "Geography", "Dark Sun", "Associated: Bluff, Thievery", "DSCS"],
    ["background650", "Road of Kings - Failed Merchant", "Geography", "Dark Sun", "Associated: Bluff, Thievery", "DSCS"],
    ["background651", "Road of Kings - Yaramite Descendant", "Geography", "Dark Sun", "Associated: Bluff, Thievery", "DSCS"],
    ["background398", "Rogue Scholar", "Racial", "General", "Associated: Stealth, Thievery", "PHR:T"],
    ["background537", "Runaway", "Occupation", "General", "Associated: Stealth, Streetwise", "Dra386"],
    ["background320", "Sage", "Occupation", "General", "Associated: Arcana, Nature", "PP"],
    ["background344", "Salvation", "Racial", "General", "Associated: Intimidate, Religion", "Dra380"],
    ["background511", "Sand Raider", "Racial", "Dark Sun", "Associated: Endurance, Stealth", "DSCS"],
    ["background390", "Sandstorm Caller", "Racial", "General", "Associated: Endurance, Nature", "PHR:D"],
    ["background282", "Sarifal", "Regional", "Faerûn", "Gain Terrain Walk in one of the following environments, allowing to bypass difficult terrain: Earth, Forest, Ice, or Swamp.", "Dra376"],
    ["background818", "Sarifal Feywarden", "", "General", "Associated: Acrobatics, Arcana, Athletics, Stealth", "Dra405"],
    ["background255", "Sarlona", "Geography", "Eberron", "Associated: Diplomacy, Endurance", "EPG"],
    ["background176", "Saved from the Noose", "", "General", "Associated: Bluff, Thievery", "Dra374"],
    ["background177", "Scholarship Student", "", "General", "Associated: Endurance", "Dra374"],
    ["background178", "Scholastic Stowaway", "", "General", "Associated: Dungeoneering, Stealth", "Dra374"],
    ["background668", "School of Unmatched Excellence", "", "General", "Associated: Diplomacy, Intimidate, The language of the mind", "PsP"],
    ["background396", "Scion of Blood", "Racial", "General", "Associated: Diplomacy, Stealth", "PHR:T"],
    ["background743", "Scion of Patricians", "Society", "General", "Associated: History, Insight", "Dra393"],
    ["background782", "Scion of Shadow", "Campaign", "Neverwinter", "Associated: Arcana, Bluff, Stealth", "NCS"],
    ["background51", "Scion of an Ancient Bloodline", "Campaign", "Scales of War", "Add History to class skill, and +3 to History.", "Dra366"],
    ["background548", "Scion of the Granite Tower", "Geography", "Faerûn", "Associated: Athletics, Stealth", "Dun177"],
    ["background30", "Scorned Noble", "Campaign", "Scales of War", "Gain +2 to saves when no allies are within 5 squares.", "Dra366"],
    ["background794", "Sea Chaplain", "", "General", "Associated: Endurance, Religion", "Dra401"],
    ["background726", "Sea Dog - Follower of Kord", "Sea Dog", "General", "Associated: Endurance, Nature", "Dra392"],
    ["background307", "Sea of Dust", "Geography", "General", "Associated: Endurance, Nature, Draconic, Primordial", "PP"],
    ["background652", "Sea of Silt - Archipelagan", "Geography", "Dark Sun", "Associated: Acrobatics, Nature, Giant", "DSCS"],
    ["background653", "Sea of Silt - Silt Pirate", "Geography", "Dark Sun", "Associated: Acrobatics, Nature, Giant", "DSCS"],
    ["background36", "Seducer", "Campaign", "Scales of War", "Add Bluff and Insight to class skill, and +1 to Bluff and Insight.", "Dra366"],
    ["background33", "Seeker for the Lost Clan", "Campaign", "Scales of War", "Add History and Dungeoneering to class skill, and +1 to History and Dungeoneering.", "Dra366"],
    ["background797", "Seeker of Illefarn", "Campaign", "Neverwinter", "Associated: Endurance, History, Nature", "Dra402"],
    ["background802", "Seeker of Rumor", "", "General", "Associated: Arcana, Stealth, Thievery, Elven", "Dra403"],
    ["background354", "Seeking Penitence", "", "General", "Associated: Endurance, History", "Dra381"],
    ["background522", "Seeking Redemption", "Racial", "Dark Sun", "Associated: Diplomacy, Insight", "DSCS"],
    ["background333", "Seer", "Occupation", "General", "Associated: Arcana, Bluff", "Dra380"],
    ["background682", "Seer (Psionic)", "Occupation", "General", "Associated: Bluff, Insight", "PsP"],
    ["background535", "Self-Improvement Expert", "Racial", "General", "Associated: Arcana, Thievery", "Dra385"],
    ["background407", "Sellsword", "Racial", "General", "Associated: Heal, Perception", "PHR:T"],
    ["background756", "Sembia (Shifter)", "Campaign", "Faerûn", "Add Bluff and Diplomacy to class skill. Add Netherese to known languages. Pass as Human when not shifting.", "Dra394"],
    ["background467", "Sentry", "Occupation", "General", "Associated: Nature, Perception", "MP2"],
    ["background527", "Servant of the Light", "Racial", "General", "Associated: Arcana, Religion, Quori", "Dra385"],
    ["background734", "Sewer Wretch", "", "General", "Associated: Arcana, Dungeoneering", "Dra392"],
    ["background218", "Shadow Acrobat", "House Phiarlan", "Eberron", "Associated: Acrobatics, Athletics", "EPG"],
    ["background247", "Shadow Marches", "Geography", "Eberron", "Associated: Heal, Nature", "EPG"],
    ["background829", "Shadowdale", "Campaign", "Encounters", "Associated: Diplomacy, Nature", "Web of the Spider Queen"],
    ["background382", "Shard of Io", "Racial", "General", "Associated: History, Religion", "PHR:D"],
    ["background473", "Shardmind - God Shard", "Racial", "General", "Associated: History, Religion", "PHB3"],
    ["background474", "Shardmind - Shard Slayer", "Racial", "General", "Associated: Arcana, Intimidate", "PHB3"],
    ["background472", "Shardmind - Thought Builder", "Racial", "General", "Associated: Arcana, Religion", "PHB3"],
    ["background236", "Sharn", "Geography", "Eberron", "Associated: Insight, Streetwise", "EPG"],
    ["background787", "Shield Dwarf", "Racial", "Neverwinter", "Associated: Dungeoneering, Endurance, Nature, Chondathan, Giant", "NCS"],
    ["background135", "Shifter - City Shifter", "Racial", "General", "Associated: Acrobatics, Streetwise", "PHB2"],
    ["background134", "Shifter - Moonspeaker", "Racial", "General", "Associated: Heal, Religion", "PHB2"],
    ["background136", "Shifter - Persecution", "Racial", "General", "Associated: Bluff, Stealth", "PHB2"],
    ["background278", "Shipmaster's Aide", "Adventurers", "Faerûn", "Associated: Athletics, History", "Dra376"],
    ["background805", "Sidhe Lord", "", "General", "Associated: Diplomacy, Intimidate", "HotF"],
    ["background815", "Sildaine", "Geography", "General", "Associated: History, Nature", "Beyond the Crystal Cave"],
    ["background39", "Silent Hunter", "Campaign", "Scales of War", "Add Stealth and Perception to class skill, and +1 to Stealth and Perception.", "Dra366"],
    ["background765", "Silver Wind's Envoy", "Campaign", "Dark Sun", "Associated: Bluff, Stealth", "Dra395"],
    ["background611", "Sisthera Master", "Racial", "General", "Associated: Acrobatics, Insight", "Dra389"],
    ["background507", "Skilled Artisan", "Racial", "Dark Sun", "Associated: Insight, Streetwise", "DSCS"],
    ["background721", "Slave", "Racial", "General", "Associated: Athletics, Endurance", "Dra392"],
    ["background87", "Society - Noble", "Society", "General", "Associated: Diplomacy, Insight", "PHB2"],
    ["background85", "Society - Poor", "Society", "General", "Associated: Streetwise", "PHB2"],
    ["background86", "Society - Wealthy", "Society", "General", "Associated: History", "PHB2"],
    ["background796", "Son of Alagondar", "Campaign", "Neverwinter", "Associated: Insight, Stealth, Streetwise", "Dra402"],
    ["background746", "Sorrowful Existence", "Racial", "General", "Associated: History, Intimidate", "Dra393"],
    ["background654", "Southern Wastes - Secret Order", "Geography", "Dark Sun", "Associated: Nature, Perception", "DSCS"],
    ["background655", "Southern Wastes - Tamwar Dervish", "Geography", "Dark Sun", "Associated: History, Nature", "DSCS"],
    ["background505", "Spellscale", "Racial", "Dark Sun", "Associated: Arcana, Intimidate", "DSCS"],
    ["background784", "Spellscarred Harbinger", "Campaign", "Neverwinter", "Associated: Arcana, Heal", "NCS"],
    ["background764", "Spirit Binder", "Campaign", "Dark Sun", "Associated: Arcana, Nature", "Dra395"],
    ["background766", "Spirit Clutch", "Campaign", "Dark Sun", "Associated: Endurance, History", "Dra395"],
    ["background544", "Spirit Hunter of the White Worm", "Geography", "Faerûn", "Associated: Nature, Endurance", "Dun177"],
    ["background607", "Spirit Possessed", "Racial", "General", "Associated: Insight, Nature", "Dra389"],
    ["background322", "Spirit Soul", "Racial", "General", "Associated: Arcana, History", "PP"],
    ["background328", "Spirit of Two Worlds", "Racial", "General", "Associated: Nature, Religion", "PP"],
    ["background549", "Spysong Troubadour", "Geography", "Faerûn", "Associated: History, Streetwise", "Dun177"],
    ["background296", "Squire", "Occupation", "General", "Associated: Athletics, Nature", "Dra378"],
    ["background355", "Stargazer (Star)", "", "General", "Associated: Insight, Perception", "Dra381"],
    ["background614", "Still Water", "Racial", "General", "Associated: Endurance, Insight", "Dra389"],
    ["background569", "Stone Runner", "Racial", "General", "Associated: Acrobatics, Athletics", "Dra387"],
    ["background735", "Stormchaser", "Racial", "General", "Associated: Arcana, Endurance", "Dra393"],
    ["background46", "Street Urchin", "Campaign", "Scales of War", "Add Intimidate and Streetwise to class skill, and +1 to Intimidate and Streetwise.", "Dra366"],
    ["background727", "Struck By Lightning - Follower of Kord", "Struck By Lightning", "General", "Associated: Bluff, Stealth", "Dra392"],
    ["background799", "Student of Callanar", "", "General", "Associated: Arcana, Bluff, History, Elven", "Dra403"],
    ["background803", "Student of Darkness", "", "General", "Associated: Arcana, Heal, Religion", "Dra403"],
    ["background800", "Student of Ironstone", "", "General", "Associated: Arcana, Athletics, Endurance, Dwarven", "Dra403"],
    ["background730", "Student of Ruald", "", "General", "Associated: Diplomacy, History", "Dra392"],
    ["background378", "Student of the Ninefold Path", "Racial", "General", "Associated: Arcana, History", "PHR:D"],
    ["background690", "Substance of Thought", "Racial", "General", "Associated: Arcana, Nature", "PsP"],
    ["background789", "Sun Elf", "Racial", "Neverwinter", "Associated: Arcana, Bluff, History, Insight, Draconic", "NCS"],
    ["background334", "Surgeon", "Occupation", "General", "Associated: Heal, Nature", "Dra380"],
    ["background297", "Survivor", "Occupation", "General", "Associated: Endurance, Stealth", "Dra378"],
    ["background563", "Survivor of Drow Raiders", "Society", "General", "Associated: Arcana, Religion, Elven", "Dra386"],
    ["background718", "Sword-for-Hire", "Racial", "General", "Associated: Athletics, Intimidate", "Dra391"],
    ["background816", "Sybaran", "Geography", "General", "Associated: History, Streetwise", "Beyond the Crystal Cave"],
    ["background656", "Tablelands - Herder", "Geography", "Dark Sun", "Associated: Diplomacy, Endurance, Thri-Kreen", "DSCS"],
    ["background658", "Tablelands - Hopeful Entrepreneur", "Geography", "Dark Sun", "Associated: Diplomacy, Endurance, Thri-Kreen", "DSCS"],
    ["background657", "Tablelands - Land's Guardian", "Geography", "Dark Sun", "Associated: Diplomacy, Endurance, Thri-Kreen", "DSCS"],
    ["background248", "Talenta Plains", "Geography", "Eberron", "Associated: Athletics, Endurance", "EPG"],
    ["background272", "Tarmalune", "Regional", "Faerûn", "When spend an action point to take an extra action, +1 to speed until the end of turn.", "Dra376"],
    ["background221", "Tasker's Dream", "House Sivis", "Eberron", "Associated: Arcana, Insight", "EPG"],
    ["background500", "Tattooed Warrior", "Racial", "Dark Sun", "Associated: Intimidate, Streetwise", "DSCS"],
    ["background546", "Telosian Scamp", "Geography", "Faerûn", "Associated: Intimidate, Streetwise", "Dun177"],
    ["background728", "Tempest's Child - Follower of Kord", "Tempest's Child", "General", "Associated: History, Religion", "Dra392"],
    ["background402", "Temple Foundling", "Racial", "General", "Associated: Endurance, Nature", "PHR:T"],
    ["background757", "Tethyr (Shifter)", "Campaign", "Faerûn", "Add Stealth to class skill. +2 bonus to Stealth. Add Chondathan or Draconic to known languages.", "Dra394"],
    ["background225", "Tharashk Gatekeeper", "House Tharashk", "Eberron", "Associated: Arcana, Nature", "EPG"],
    ["background223", "Tharashk Prospector", "House Tharashk", "Eberron", "Associated: Dungeoneering, Nature", "EPG"],
    ["background25", "Thay", "Campaign", "Faerûn", "Add the higher of Intelligence score or Constitution score to starting hit points.", "FRPG"],
    ["background600", "The Basilisk Society", "Origin", "General", "Associated: Nature, Streetwise", "Dra389"],
    ["background482", "The Breach", "Geography", "General", "Associated: Arcana, Endurance, Primordial", "Dra383"],
    ["background748", "The Dalelands (Shifter)", "Campaign", "Faerûn", "Add Stealth and Nature to class skill. +2 bonus to Stealth. While shifting, +2 bonus to Intimidate.", "Dra394"],
    ["background602", "The Demon Binder", "Origin", "General", "Associated: Arcana, Religion", "Dra389"],
    ["background603", "The Five Wraiths", "Origin", "General", "Associated: Acrobatics, Athletics", "Dra389"],
    ["background253", "The Frostfell (Eberron Player's Guide)", "Geography", "Eberron", "Associated: Endurance, Nature", "EPG"],
    ["background751", "The Great Dale (Shifter)", "Campaign", "Faerûn", "Reroll any Nature. Add Elven to known languages.", "Dra394"],
    ["background601", "The High One Falls", "Origin", "General", "Associated: Endurance, Intimidate", "Dra389"],
    ["background671", "The Path of Thirty-Seven Obstacles", "", "General", "Associated: Endurance, Insight", "PsP"],
    ["background692", "The Wide-Open Mind", "Racial", "General", "Associated: Nature, Streetwise", "PsP"],
    ["background713", "Theologist", "", "General", "Associated: History, Religion", "Dra390"],
    ["background530", "Thoughtsinger", "Racial", "General", "Associated: Diplomacy, Insight, Quori", "Dra385"],
    ["background213", "Thousand Yard Stare", "House Medani", "Eberron", "Associated: Endurance, Perception", "EPG"],
    ["background239", "Thrane", "Geography", "Eberron", "Associated: Intimidate,Religion", "EPG"],
    ["background308", "Thunderpeaks", "Geography", "General", "Associated: Athletics, Dungeoneering, Dwarven, Giant", "PP"],
    ["background226", "Thuranni Stonespur Recruit", "House Thuranni", "Eberron", "Associated: Acrobatics, Stealth", "EPG"],
    ["background138", "Tiefling - Dark Secret", "Racial", "General", "Associated: Arcana, Dungeoneering", "PHB2"],
    ["background139", "Tiefling - Infernal Nightmares", "Racial", "General", "Associated: Bluff, Religion", "PHB2"],
    ["background137", "Tiefling - Merchant Dynasty", "Racial", "General", "Associated: Streetwise", "PHB2"],
    ["background335", "Tomb Robber", "Occupation", "General", "Associated: Stealth, Thievery", "Dra380"],
    ["background532", "Too Many Secrets", "Occupation", "General", "Associated: Insight, Streetwise, Abyssal", "Dra385"],
    ["background610", "Totemic Ally", "Racial", "General", "Associated: Insight, Nature", "Dra389"],
    ["background169", "Touched by Darkness", "Legacy of Acererak", "General", "Associated: Intimidate, Stealth, Religion. +1 to saves against necrotic effects.", "Dra371"],
    ["background192", "Touched by an Angel", "Divine", "General", "Associated: Arcana, Perception", "DP"],
    ["background801", "Tower Graduate", "", "General", "Associated: Arcana, History, Religion", "Dra403"],
    ["background62", "Trained from Birth for a Specific Prophecy", "Campaign", "Scales of War", "Once per day, can reroll an initiative if don't like the result.", "Dra366"],
    ["background567", "Trapped in the Feywild", "Occupation", "General", "Associated: Arcana, Endurance, Elven", "Dra387"],
    ["background55", "Traveling Missionary", "Campaign", "Scales of War", "Learn an extra language, add Religion to class skill, and gain a +2 to Religion.", "Dra366"],
    ["background575", "Treasure Hunter", "", "General", "Associated: Arcana, History", "HS1"],
    ["background795", "Tree Talker", "", "General", "Associated: Athletics, Streetwise", "Dra401"],
    ["background806", "Tuathan", "", "General", "Associated: Endurance, History", "HotF"],
    ["background594", "Turathi Inquisitor", "Racial", "General", "Associated: Bluff, Intimidate", "Dra388"],
    ["background373", "Turathi Slave Clan", "Racial", "General", "Associated: Arcana, Streetwise", "PHR:D"],
    ["background672", "Twilight Dreamers", "", "General", "Associated: Arcana, Dungeoneering, Religion", "PsP"],
    ["background585", "Two Sides of the Coin", "", "General", "Associated: Bluff, Insight", "Dra388"],
    ["background26", "Tymanther", "Campaign", "Faerûn", "Add Athletics to class skill, and +2 to Athletics.", "FRPG"],
    ["background618", "Tyr - Embedded Spy", "Geography", "Dark Sun", "Associated: Endurance, Streetwise, Elven", "DSCS"],
    ["background619", "Tyr - Freed Slave", "Geography", "Dark Sun", "Associated: Endurance, Streetwise, Elven", "DSCS"],
    ["background620", "Tyr - Noble of Conscience", "Geography", "Dark Sun", "Associated: Endurance, Streetwise, Elven", "DSCS"],
    ["background621", "Tyr - Revolutionary", "Geography", "Dark Sun", "Associated: Endurance, Streetwise, Elven", "DSCS"],
    ["background324", "Underdark Survivor", "Racial", "General", "Associated: Dungeoneering, Nature", "PP"],
    ["background309", "Underwild", "Geography", "General", "Associated: Dungeoneering, Perception, Deep Speech, Elven", "PP"],
    ["background397", "Unfettered Future", "Racial", "General", "Associated: History, Insight", "PHR:T"],
    ["background555", "Unhomed", "Racial", "General", "Associated: Athletics, Bluff, Perception, Any language except Abyssal or Supernal", "Dra386"],
    ["background411", "Unlikely Primal Hero", "Racial", "General", "Associated: Bluff, Streetwise", "PHR:T"],
    ["background807", "Unseelie Agent", "", "General", "Associated: Arcana, Stealth", "HotF"],
    ["background267", "Unstoppable Soldier", "Racial", "Eberron", "Associated: Athletics, Endurance", "EPG"],
    ["background277", "Upperdark Slave", "Adventurers", "Faerûn", "Associated: Dungeoneering, Endurance", "Dra376"],
    ["background485", "Urban Gnome", "Racial", "General", "Associated: Diplomacy, Streetwise", "Dra384"],
    ["background570", "Urban Shaman", "Racial", "General", "Associated: Diplomacy, Streetwise. Substitude Streetwise for Nature on rituals when in urban.", "Dra387"],
    ["background659", "Urik - Gifted Potter", "Geography", "Dark Sun", "Associated: Insight, Streetwise", "DSCS"],
    ["background660", "Urik - Scarred Miner", "Geography", "Dark Sun", "Associated: Insight, Streetwise", "DSCS"],
    ["background661", "Urik - Watchful Astronomer", "Geography", "Dark Sun", "Associated: Insight, Streetwise", "DSCS"],
    ["background779", "Uthgardt Barbarian", "Campaign", "Neverwinter", "Associated: Athletics, Nature", "NCS"],
    ["background231", "Vadalis Botanist", "House Vadalis", "Eberron", "Associated: Heal, Nature", "EPG"],
    ["background230", "Vadalis Griffon Rider", "House Vadalis", "Eberron", "Associated: Acrobatics, Nature", "EPG"],
    ["background229", "Vadalis Handler", "House Vadalis", "Eberron", "Associated: Dungeoneering, Nature", "EPG"],
    ["background249", "Valenar", "Geography", "Eberron", "Associated: Acrobatics, Athletics", "EPG"],
    ["background550", "Vault-Warden of the Lost Ways", "Geography", "Faerûn", "Associated: Dungeoneering, Endurance", "Dun177"],
    ["background509", "Veiled Warrior", "Racial", "Dark Sun", "Associated: Nature, Stealth", "DSCS"],
    ["background342", "Vengeance", "Racial", "General", "Associated: Endurance, Intimidate", "Dra380"],
    ["background409", "Vengeful Royalty", "Racial", "General", "Associated: Endurance, Nature, Perception", "PHR:T"],
    ["background72", "Vet Who Can't Let Go", "Campaign", "Scales of War", "Add History and Intimidate to class skill, and +1 to History and Intimidate.", "Dra366"],
    ["background193", "Veteran of a Religious War", "Divine", "General", "Associated: Athletics, Intimidate", "DP"],
    ["background561", "Veteran of the Arena", "Racial", "General", "Associated: Athletics, Endurance", "Dra386"],
    ["background691", "Victim of Superstition", "Racial", "General", "Associated: Bluff, Stealth", "PsP"],
    ["background265", "Vigilant", "Racial", "Eberron", "Associated: Insight, Intimidate", "EPG"],
    ["background275", "Vigilant Informant", "Adventurers", "Faerûn", "Associated: Streetwise, Thievery", "Dra376"],
    ["background812", "Vile Scholar", "", "General", "Associated: Arcana, History", "The Book of Vile Darkness"],
    ["background27", "Vilhon Wilds", "Campaign", "Faerûn", "Can reroll any Dungeoneering.", "FRPG"],
    ["background557", "Voice of Pelor", "Racial", "General", "Associated: History, Religion", "Dra386"],
    ["background685", "Voice of a Dozen Generations", "Racial", "General", "Associated: Diplomacy, History", "PsP"],
    ["background683", "Wanderer", "Occupation", "General", "Associated: Nature, Perception", "PsP"],
    ["background29", "Wandering Duelist", "Campaign", "Scales of War", "Add Intimidate to class skill and give yourself a +3 to Intimidate.", "Dra366"],
    ["background203", "Wandering Inn Traveler", "House Ghallanda", "Eberron", "Associated: Endurance, Streetwise", "EPG"],
    ["background707", "Wandering Master", "Occupation", "General", "Associated: History, Nature, Any one, except for Infernal and Supernal", "Dra390"],
    ["background44", "Wandering Mercenary", "Campaign", "Scales of War", "It takes four failed death saves to kill you.", "Dra366"],
    ["background591", "Wandering Zealot", "Racial", "General", "Associated: Diplomacy, Endurance", "Dra388"],
    ["background222", "War Courier", "House Sivis", "Eberron", "Associated: Athletics, Stealth", "EPG"],
    ["background577", "Ward of the State", "Occupation", "General", "Associated: Insight, Streetwise", "Dra387"],
    ["background194", "Ward of the Temple", "Divine", "General", "Associated: Heal, Religion", "DP"],
    ["background34", "Warsmith", "Campaign", "Scales of War", "Can construct weapons and armor. Can cast Creation rituals as if you have Ritual Caster.", "Dra366"],
    ["background1", "Waterdeep", "Campaign", "Faerûn", "Know one language, add Diplomacy to class skill, and +2 to Diplomacy.", "FRPG"],
    ["background554", "Wayfinder", "Racial", "General", "Associated: Endurance, Nature", "Dra386"],
    ["background664", "Western Hinterlands - Feral Foundling", "Geography", "Dark Sun", "Associated: Nature, Stealth, Thri-Kreen", "DSCS"],
    ["background662", "Western Hinterlands - Hunting Tribe", "Geography", "Dark Sun", "Associated: Nature, Stealth, Thri-Kreen", "DSCS"],
    ["background663", "Western Hinterlands - Outcast", "Geography", "Dark Sun", "Associated: Nature, Stealth, Thri-Kreen", "DSCS"],
    ["background480", "White Riders", "Racial", "General", "Associated: Intimidate, Nature", "Dra384"],
    ["background790", "Wild Elf", "Racial", "Neverwinter", "Associated: Nature, Perception, Stealth", "NCS"],
    ["background321", "Wild Hunter", "Occupation", "General", "Associated: Athletics, Nature", "PP"],
    ["background582", "Wilden - Ancient One", "Racial", "General", "Associated: History, Nature", "Dra388"],
    ["background179", "Wilden - Born of Ruin", "Racial", "General", "Associated: Arcana, Nature", "PHB3"],
    ["background583", "Wilden - Destroyer", "Racial", "General", "Associated: Intimidate, Stealth", "Dra388"],
    ["background180", "Wilden - Estranged Fey", "Racial", "General", "Associated: Endurance, Nature", "Dra374"],
    ["background181", "Wilden - Hunted", "Racial", "General", "Associated: Bluff, Stealth", "PHB3"],
    ["background584", "Wilden - Hunter", "Racial", "General", "Associated: Dungeoneering, Stealth", "Dra388"],
    ["background386", "Wilderness Loner", "Racial", "General", "Associated: Endurance, Nature", "PHR:D"],
    ["background276", "Windrise Ports", "Regional", "Faerûn", "Add one skill to your class skill list, and gain one additional language.", "Dra376"],
    ["background813", "Winterguard Marshal", "", "General", "Associated: Perception, Streetwise, Elven", "Dra405"],
    ["background481", "Wintertouched", "Racial", "General", "Associated: Arcana, Stealth", "Dra384"],
    ["background762", "Witch", "Occupation", "General", "Associated: Arcana, Heal, Nature", "Dra394"],
    ["background617", "Witness", "Occupation", "General", "Associated: Insight, Perception", "Dra378"],
    ["background791", "Wood Elf", "Racial", "Neverwinter", "Associated: Diplomacy, Insight, Nature, Chondathan, Damaran, Dwarven, Giant, Goblin", "NCS"],
    ["background346", "World Walker", "", "General", "Associated: Arcana, Nature", "Dra380"],
    ["background310", "Wrathwood", "Geography", "General", "Associated: Perception, Stealth, Elven", "PP"],
    ["background581", "Wrongs to be Righted", "", "General", "Associated: Endurance, Intimidate", "Dra387"],
    ["background256", "Xen'drik", "Geography", "Eberron", "Associated: Nature", "EPG"],
    ["background53", "Young Cutthroat", "Campaign", "Scales of War", "Add Intimidate and Thievery to class skill, and +1 to Intimidate and Thievery.", "Dra366"],
    ["background551", "Zhengyian Blood Mage", "Geography", "Faerûn", "Associated: Arcana, Bluff", "Dun177"],
    ["background250", "Zilargo", "Geography", "Eberron", "Associated: Bluff, Insight", "EPG"]
])