od.reader.jsonp_data_listing(20130703, "companion", ["ID", "Name", "Type", "Size", "CreatureType", "SourceBook"], [
    ["associate5", "Bear Animal Companion", "Animal Companion", "Medium", "Beast, Natural", "HotFK"],
    ["associate64", "Living Zephyr", "Animal Companion", "Medium", "Beast, Elemental, Magical", "HotEC"],
    ["associate58", "Quasit Companion", "Animal Companion", "Tiny", "Demon, Elemental, Humanoid", "The Book of Vile Darkness"],
    ["associate1", "Wolf Animal Companion", "Animal Companion", "Medium", "Beast, Natural", "HotFK"],
    ["companion1", "Bear", "Companion", "Medium", "Beast, Natural", "MP"],
    ["companion2", "Boar", "Companion", "Medium", "Beast, Natural", "MP"],
    ["companion3", "Cat", "Companion", "Medium", "Beast, Natural", "MP, HotF"],
    ["companion90", "Horse", "Companion", "Medium or Large", "Beast, Mount, Natural", "Dra392"],
    ["companion4", "Lizard", "Companion", "Medium", "Beast, Natural, Reptile", "MP"],
    ["companion5", "Raptor", "Companion", "Small", "Beast, Natural", "MP"],
    ["companion6", "Serpent", "Companion", "Medium", "Beast, Natural, Reptile", "MP, HotF"],
    ["companion91", "Simian", "Companion", "Small or Medium", "Beast, Natural", "Dra392"],
    ["companion7", "Spider", "Companion", "Medium", "Beast, Natural", "MP"],
    ["companion54", "Vadalis-bred Griffon", "Companion", "Large", "Beast, Mount, Natural", "EPG"],
    ["companion8", "Wolf", "Companion", "Medium", "Beast, Natural", "MP"],
    ["associate79", "Arctine", "Elemental Companion", "Small", "Cold, Elemental, Humanoid", "HotEC"],
    ["associate80", "Automaton", "Elemental Companion", "Small", "Construct, Elemental, Humanoid", "HotEC"],
    ["associate81", "Chaos Phage", "Elemental Companion", "Small", "Beast, Elemental, Magical", "HotEC"],
    ["associate84", "Crysmalite", "Elemental Companion", "Small", "Beast, Elemental, Magical, Spider", "HotEC"],
    ["associate85", "Flame Serpent", "Elemental Companion", "Small", "Beast, Elemental, Fire, Magical", "HotEC"],
    ["associate86", "Hordeling", "Elemental Companion", "Small", "Demon, Elemental, Humanoid", "HotEC"],
    ["associate88", "Magmin", "Elemental Companion", "Medium", "Earth, Elemental, Fire, Humanoid", "HotEC"],
    ["associate87", "Mud Wretch", "Elemental Companion", "Small", "Beast, Earth, Elemental, Magical, Water", "HotEC"],
    ["associate89", "Nereid", "Elemental Companion", "Small", "Aquatic, Elemental, Humanoid, Water", "HotEC"],
    ["associate90", "Pech", "Elemental Companion", "Small", "Earth, Elemental, Humanoid", "HotEC"],
    ["associate91", "Storm Talon", "Elemental Companion", "Small", "Beast, Elemental, Magical", "HotEC"],
    ["associate92", "Sylph", "Elemental Companion", "Medium", "Air, Elemental, Humanoid", "HotEC"],
    ["companion36", "Air Mephit", "Familiar", "Tiny", "", "Dra374"],
    ["companion70", "Ambush Vine Shoot", "Familiar", "Tiny", "", "Dra377"],
    ["companion23", "Arcane Eye", "Familiar", "Tiny", "", "Dra374"],
    ["companion37", "Arcane Wisp", "Familiar", "Tiny", "", "Dra374"],
    ["companion24", "Badger", "Familiar", "Tiny", "", "Dra374"],
    ["companion56", "Bantam Fastieth", "Familiar", "Tiny", "", "Dra377"],
    ["companion9", "Bat", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion38", "Beholderkin", "Familiar", "Tiny", "", "Dra374"],
    ["companion39", "Blackspawn Darkling", "Familiar", "Tiny", "", "Dra374"],
    ["companion50", "Blazing Skull", "Familiar", "Tiny", "", "Dra374"],
    ["companion57", "Bloodthorn Vine Barb", "Familiar", "Tiny", "", "Dra377"],
    ["companion40", "Bluespawn Nimblespark", "Familiar", "Tiny", "", "Dra374"],
    ["companion10", "Book Imp", "Familiar", "Tiny", "", "AP"],
    ["companion12", "Bound Demon", "Familiar", "Tiny", "", "AP"],
    ["companion114", "Brownie", "Familiar", "Tiny", "", "Dra420"],
    ["companion25", "Canine Construct", "Familiar", "Tiny", "", "Dra374"],
    ["companion20", "Cat", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion51", "Chaos Shard", "Familiar", "Tiny", "", "Dra374"],
    ["companion58", "Clockwork Scorpion", "Familiar", "Tiny", "", "Dra377"],
    ["companion89", "Coure Attendant", "Familiar", "Tiny", "", "HotF"],
    ["companion14", "Crafter Homunculus", "Familiar", "Tiny", "", "AP"],
    ["companion71", "Crawling Clot", "Familiar", "Tiny", "", "Dra377"],
    ["companion93", "Critic Lizard", "Familiar", "Tiny", "", "Dra397"],
    ["companion105", "Daolanin", "Familiar", "Tiny", "", "HotEC"],
    ["companion72", "Dimensional Pet", "Familiar", "Tiny", "", "Dra377"],
    ["companion26", "Disembodied Hand", "Familiar", "Tiny", "", "Dra374"],
    ["companion106", "Djinnling", "Familiar", "Tiny", "", "HotEC"],
    ["companion15", "Dragonling", "Familiar", "Tiny", "", "AP"],
    ["companion59", "Dragonmark Reflection", "Familiar", "Tiny", "", "Dra377"],
    ["companion41", "Earth Mephit", "Familiar", "Tiny", "", "Dra374"],
    ["companion107", "Efreetkin", "Familiar", "Tiny", "", "HotEC"],
    ["companion16", "Falcon", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion87", "Fiddling Grig", "Familiar", "Tiny", "", "HotF"],
    ["companion27", "Fire Lizard", "Familiar", "Tiny", "", "Dra374"],
    ["companion42", "Fire Mephit", "Familiar", "Tiny", "", "Dra374"],
    ["companion94", "Floating Polyp", "Familiar", "Tiny", "", "Dra397"],
    ["companion60", "Floating Weapon", "Familiar", "Tiny", "", "Dra377"],
    ["companion61", "Gadfly", "Familiar", "Tiny", "", "Dra377"],
    ["companion81", "Gallant Hawk", "Familiar", "Tiny", "", "Dra382"],
    ["companion52", "Gibbering Pet", "Familiar", "Tiny", "", "Dra374"],
    ["companion43", "Grayspawn Shortfang", "Familiar", "Tiny", "", "Dra374"],
    ["companion44", "Greenspawn Banespeak", "Familiar", "Tiny", "", "Dra374"],
    ["companion95", "Hurrum", "Familiar", "Tiny", "", "Dra397"],
    ["companion45", "Ice Mephit", "Familiar", "Tiny", "", "Dra374"],
    ["companion96", "Jank", "Familiar", "Tiny", "", "Dra397"],
    ["companion97", "Kes'trekel", "Familiar", "Tiny", "", "Dra397"],
    ["companion98", "Kivit", "Familiar", "Tiny", "", "Dra397"],
    ["companion84", "Least Air Elemental", "Familiar", "Tiny", "", "Dra382"],
    ["companion86", "Least Earth Elemental", "Familiar", "Tiny", "", "Dra382"],
    ["companion28", "Lightning Lizard", "Familiar", "Tiny", "", "Dra374"],
    ["companion77", "Lingering Nightmare", "Familiar", "Tiny", "", "Dra377"],
    ["companion73", "Living Infusion", "Familiar", "Tiny", "", "Dra377"],
    ["companion62", "Magpie", "Familiar", "Tiny", "", "Dra377"],
    ["companion108", "Maridan", "Familiar", "Tiny", "", "HotEC"],
    ["companion63", "Marmoset", "Familiar", "Tiny", "", "Dra377"],
    ["companion74", "Minor Foulspawn", "Familiar", "Tiny", "", "Dra377"],
    ["companion82", "Moon Wisp", "Familiar", "Tiny", "", "Dra382"],
    ["companion79", "Muse Sprite", "Familiar", "Tiny", "", "Dra382"],
    ["companion64", "Octopus", "Familiar", "Tiny", "", "Dra377"],
    ["companion29", "Ooze", "Familiar", "Tiny", "", "Dra374"],
    ["companion55", "Oso de la Fez, Former Show Bear", "Familiar", "Tiny", "", "Dra376"],
    ["companion11", "Owl", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion30", "Parrot", "Familiar", "Tiny", "", "Dra374"],
    ["companion46", "Rakshasa Claw", "Familiar", "Tiny", "", "Dra374"],
    ["companion18", "Rat", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion19", "Raven", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion47", "Redspawn Spitfire", "Familiar", "Tiny", "", "Dra374"],
    ["companion31", "Rootling", "Familiar", "Tiny", "", "Dra374"],
    ["companion65", "Saddle Squire", "Familiar", "Tiny", "", "Dra377"],
    ["companion32", "Scout Homunculus", "Familiar", "Tiny", "", "Dra374"],
    ["companion21", "Serpent", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion53", "Shadow Incarnate", "Familiar", "Tiny", "", "Dra374"],
    ["companion92", "Shadow Raven", "Familiar", "Tiny", "", "HoS"],
    ["companion78", "Silver Lamp", "Familiar", "Tiny", "", "Dra377"],
    ["companion99", "Sitak", "Familiar", "Tiny", "", "Dra397"],
    ["companion33", "Skull", "Familiar", "Tiny", "", "Dra374"],
    ["companion75", "Smith's Hammer", "Familiar", "Tiny", "", "Dra377"],
    ["companion66", "Soarwood Wings", "Familiar", "Tiny", "", "Dra377"],
    ["companion83", "Specter", "Familiar", "Tiny", "", "Dra382"],
    ["companion22", "Spider", "Familiar", "Tiny", "", "AP, HotF"],
    ["companion113", "Spiderling of Lolth", "Familiar", "Tiny", "", "Dra413"],
    ["companion102", "Sprite", "Familiar", "Tiny", "", "HotF"],
    ["companion48", "Stone Fowl", "Familiar", "Tiny", "", "Dra374"],
    ["companion67", "Summoner Homunculus", "Familiar", "Tiny", "", "Dra377"],
    ["companion76", "Tinker Feyling", "Familiar", "Tiny", "", "Dra377"],
    ["companion85", "Tiny Gelatinous Cube", "Familiar", "Tiny", "", "Dra382"],
    ["companion34", "Toad", "Familiar", "Tiny", "", "Dra374"],
    ["companion68", "Tome Caddy", "Familiar", "Tiny", "", "Dra377"],
    ["companion69", "Warforged Faceplate", "Familiar", "Tiny", "", "Dra377"],
    ["companion35", "Weasel", "Familiar", "Tiny", "", "Dra374"],
    ["companion80", "White-Eyed Crow", "Familiar", "Tiny", "", "Dra382"],
    ["companion49", "Whitespawn Snowstepper", "Familiar", "Tiny", "", "Dra374"],
    ["companion100", "Wrab", "Familiar", "Tiny", "", "Dra397"],
    ["companion101", "Z'tal", "Familiar", "Tiny", "", "Dra397"],
    ["associate53", "Trained Blink Dog", "Fey Beast Companion", "Medium", "Beast, Fey", "HotF"],
    ["associate54", "Trained Displacer Beast", "Fey Beast Companion", "Medium", "Beast, Fey", "HotF"],
    ["associate55", "Trained Fey Panther", "Fey Beast Companion", "Medium", "Beast, Fey", "HotF"],
    ["associate56", "Trained Young Owlbear", "Fey Beast Companion", "Medium", "Beast, Fey", "HotF"],
    ["associate13", "Celestial Battle Tiger", "Mount", "Large", "Beast, Immortal, Mount", "Dra393"],
    ["associate14", "Celestial Behemoth", "Mount", "Large", "Beast, Immortal, Mount", "Dra393"],
    ["associate15", "Celestial Pegasus", "Mount", "Large", "Beast, Immortal, Mount", "Dra393"],
    ["associate12", "Celestial Warhorse", "Mount", "Large", "Beast, Immortal, Mount", "Dra393"],
    ["associate16", "Silver Dragon Steed", "Mount", "Large", "Beast, Dragon, Immortal, Magical, Mount", "Dra393"],
    ["associate63", "Unicorn Destrier", "Mount", "Large", "Beast, Fey, Magical, Mount", "Dra406"],
    ["associate66", "Air Archon Grunt", "Summoned Creature", "Medium", "Air, Elemental, Humanoid", "HotEC"],
    ["associate75", "Air Monolith", "Summoned Creature", "Large", "Air, Beast, Elemental, Magical", "HotEC"],
    ["associate61", "Ancestral Defender", "Summoned Creature", "Medium", "Animate, Natural", "Dra405"],
    ["associate45", "Blue Dragon Wyrmling", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate43", "Bulette", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate65", "Chariot of Sustarre", "Summoned Creature", "Gargantuan", "Beast, Elemental, Fire, Magical", "HotEC"],
    ["associate25", "Dark Creeper", "Summoned Creature", "Small", "Humanoid, Shadow", "HoS"],
    ["associate42", "Desert Hawk", "Summoned Creature", "Medium", "Beast, Natural", "HotF"],
    ["associate46", "Desert Roc", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate49", "Dire Bear", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate51", "Dire Lion", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate83", "Displacer Beast", "Summoned Creature", "Large", "Beast, Fey, Magical", "Dra406"],
    ["associate24", "Doom Hulk", "Summoned Creature", "Large", "Aberrant, Animate", "HoS"],
    ["associate94", "Duodrone Balancer", "Summoned Creature", "Medium", "Animate, Immortal, Modron", "Dra414"],
    ["associate67", "Earth Archon Grunt", "Summoned Creature", "Medium", "Earth, Elemental, Humanoid", "HotEC"],
    ["associate76", "Earth Monolith", "Summoned Creature", "Large", "Beast, Earth, Elemental, Magical", "HotEC"],
    ["associate70", "Earth Titan Warrior", "Summoned Creature", "Huge", "Earth, Elemental, Giant, Humanoid", "HotEC"],
    ["associate93", "Earth-Friend", "Summoned Creature", "Tiny", "Beast, Earth, Elemental, Magical", "DSH"],
    ["associate32", "Elemental Warrior (Air)", "Summoned Creature", "Large", "Air, Elemental, Humanoid", "HotEC"],
    ["associate33", "Elemental Warrior (Earth)", "Summoned Creature", "Large", "Earth, Elemental, Humanoid", "HotEC"],
    ["associate34", "Elemental Warrior (Fire)", "Summoned Creature", "Large", "Elemental, Fire, Humanoid", "HotEC"],
    ["associate37", "Elemental Warrior (Water)", "Summoned Creature", "Large", "Elemental, Humanoid, Water", "HotEC"],
    ["associate68", "Fire Archon Grunt", "Summoned Creature", "Medium", "Elemental, Fire, Humanoid", "HotEC"],
    ["associate77", "Fire Monolith", "Summoned Creature", "Large", "Beast, Elemental, Fire, Magical", "HotEC"],
    ["associate71", "Fire Titan Warrior", "Summoned Creature", "Huge", "Elemental, Fire, Giant, Humanoid", "HotEC"],
    ["associate62", "Flame Zephyr", "Summoned Creature", "Small", "Air, Beast, Elemental, Fire, Magical", "HotEC"],
    ["associate72", "Frost Titan Warrior", "Summoned Creature", "Huge", "Cold, Elemental, Giant, Humanoid", "HotEC"],
    ["associate7", "Frostblight Treant Protector", "Summoned Creature", "Huge", "Beast, Fey", "HotFK"],
    ["associate40", "Giant Cobra", "Summoned Creature", "Medium", "Beast, Natural", "HotF"],
    ["associate22", "Gloom Beast", "Summoned Creature", "Large", "Humanoid, Shadow", "HoS"],
    ["associate47", "Grizzly Bear", "Summoned Creature", "Medium", "Beast, Natural", "HotF"],
    ["associate50", "Hunting Tiger", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate74", "Invisible Stalker", "Summoned Creature", "Large", "Air, Elemental, Humanoid", "HotEC"],
    ["associate17", "Jade Horse", "Summoned Creature", "Large", "Beast, Construct, Mount, Natural", "Dra393"],
    ["associate19", "Mourning Handmaiden", "Summoned Creature", "Medium", "Fey, Humanoid, Undead", "Dra393"],
    ["associate48", "Pack Wolf", "Summoned Creature", "Medium", "Beast, Natural", "HotF"],
    ["associate9", "Pit Fiend Servitor", "Summoned Creature", "Large", "Humanoid, Immortal", "HotFK"],
    ["associate52", "Raptor Behemoth", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate60", "Sarifal Advisor", "Summoned Creature", "Tiny", "Fey, Humanoid", "Dra405"],
    ["associate82", "Satyr of the Night", "Summoned Creature", "Medium", "Fey, Humanoid", "Dra406"],
    ["associate39", "Servant of the Staff", "Summoned Creature", "Medium", "Humanoid, Shadow", "MME"],
    ["associate28", "Shadow Beast", "Summoned Creature", "Medium", "Beast, Shadow", "HoS"],
    ["associate30", "Shadow Brute", "Summoned Creature", "Large", "Beast, Shadow", "HoS"],
    ["associate21", "Shadow Lurk", "Summoned Creature", "Medium", "Humanoid, Shadow", "HoS"],
    ["associate38", "Shadow Serpent", "Summoned Creature", "Small", "Beast, Shadow", "HoS"],
    ["associate27", "Shadow Skeleton", "Summoned Creature", "Medium", "Animate, Shadow, Undead", "HoS"],
    ["associate29", "Shadow Wraith", "Summoned Creature", "Medium", "Humanoid, Shadow, Undead", "HoS"],
    ["associate57", "Sidhe House Guard", "Summoned Creature", "Medium", "Fey, Humanoid", "HotF"],
    ["associate18", "Silt Elemental", "Summoned Creature", "Medium", "Air, Beast, Earth, Elemental, Magical", "Dun184"],
    ["associate59", "Skeletal Warrior", "Summoned Creature", "Medium", "Animate, Shadow, Undead", "The Book of Vile Darkness"],
    ["associate26", "Sorrowsworn", "Summoned Creature", "Medium", "Humanoid, Shadow", "HoS"],
    ["associate23", "Soul Eater", "Summoned Creature", "Medium", "Aberrant, Animate", "HoS"],
    ["associate20", "Spectral Protector", "Summoned Creature", "Medium", "Fey, Humanoid, Undead", "Dra393"],
    ["associate8", "Spined Devil Lackey", "Summoned Creature", "Medium", "Humanoid, Immortal", "HotFK"],
    ["associate73", "Storm Titan Warrior", "Summoned Creature", "Huge", "Aquatic, Elemental, Giant, Humanoid", "HotEC"],
    ["associate10", "Thought Phantom", "Summoned Creature", "Medium", "Aberrant, Beast, Magical", "Dra393"],
    ["associate31", "Undead Soldier", "Summoned Creature", "Medium", "Animate, Natural, Undead", "HoS"],
    ["associate44", "Venomous Scorpion", "Summoned Creature", "Large", "Beast, Natural", "HotF"],
    ["associate69", "Water Archon Grunt", "Summoned Creature", "Medium", "Aquatic, Elemental, Humanoid, Water", "HotEC"],
    ["associate78", "Water Monolith", "Summoned Creature", "Large", "Beast, Elemental, Magical, Water", "HotEC"],
    ["associate11", "Way Walker", "Summoned Creature", "Huge", "Aberrant, Beast, Magical", "Dra393"],
    ["associate6", "Wood Woad Guardian", "Summoned Creature", "Medium", "Fey, Humanoid, Plant", "HotFK"]
])