od.reader.jsonp_data_listing(20130703, "epicdestiny", ["ID", "Name", "Prerequisite", "SourceBook"], [
    ["epicdestiny199", "Adamantine Soldier", "Fighter or warlord", "MP"],
    ["epicdestiny335", "Arcane Sword", "Swordmage", "AP"],
    ["epicdestiny336", "Archlich", "Any arcane class", "AP"],
    ["epicdestiny13", "Archmage", "Wizard", "PHB"],
    ["epicdestiny337", "Archspell", "Any arcane class", "AP"],
    ["epicdestiny729", "Avangion", "Any arcane class", "DSCS"],
    ["epicdestiny430", "Avatar of Death", "Death Knell feat", "DP"],
    ["epicdestiny431", "Avatar of Freedom", "Path of Freedom feat", "DP"],
    ["epicdestiny432", "Avatar of Hope", "Hope Remains feat", "DP"],
    ["epicdestiny538", "Avatar of Io", "Dragonborn", "PHR:D"],
    ["epicdestiny433", "Avatar of Justice", "Immediate Justice feat", "DP"],
    ["epicdestiny434", "Avatar of Life", "Pulse of Life feat", "DP"],
    ["epicdestiny435", "Avatar of Storm", "Storm Sacrifice feat", "DP"],
    ["epicdestiny436", "Avatar of War", "Path of War feat", "DP"],
    ["epicdestiny464", "Bahamut's Vessel", "Must worship Bahamut", "Dra378"],
    ["epicdestiny200", "Beastlord", "Ranger, Beast Mastery class feature", "MP"],
    ["epicdestiny689", "Ceaseless Guardian", "Any defender class", "Dra387"],
    ["epicdestiny387", "Champion of Prophecy", "", "EPG"],
    ["epicdestiny146", "Chosen", "Any divine class", "FRPG, DP"],
    ["epicdestiny762", "Cosmic Soul", "Any psionic class", "PsP"],
    ["epicdestiny201", "Dark Wanderer", "Ranger or rogue", "MP"],
    ["epicdestiny296", "Darklord", "", "Dra372"],
    ["epicdestiny844", "Dead God Avatar", "Must worship a dead deity, divine power source", "Dra390"],
    ["epicdestiny58", "Deadly Trickster", "Dexterity 21 or Charisma 21; training in Acrobatics, Bluff, Stealth, or Thievery", "PHB"],
    ["epicdestiny54", "Demigod", "", "PHB"],
    ["epicdestiny763", "Demiurge", "Any psionic class", "PsP"],
    ["epicdestiny797", "Destined Scion", "", "HotFK"],
    ["epicdestiny613", "Diamond Soul", "Monk", "PHB3"],
    ["epicdestiny644", "Disincarnate", "Deva, memory of a thousand lifetimes power", "Dra385"],
    ["epicdestiny388", "Dispossesed Champion", "", "EPG"],
    ["epicdestiny696", "Draconic Incarnation", "Any arcane class", "Dra388"],
    ["epicdestiny730", "Dragon King", "Arcane defiling power", "DSCS"],
    ["epicdestiny582", "Dragonheart", "Any martial class", "MP2"],
    ["epicdestiny764", "Eighth Seal", "Any psionic class", "PsP"],
    ["epicdestiny209", "Elf High Mage", "Wizard; eladrin or elf", "Dra367"],
    ["epicdestiny969", "Emergent Primordial", "Elemental origin, Born of the Elements feat, or any elemental power", "HotEC"],
    ["epicdestiny202", "Eternal Defender", "Fighter", "MP"],
    ["epicdestiny56", "Eternal Seeker", "", "PHB"],
    ["epicdestiny448", "Exalted Angel", "Any divine class", "DP"],
    ["epicdestiny933", "Exemplar of Evil", "Evil alignment", "The Book of Vile Darkness"],
    ["epicdestiny503", "Fang of the World Serpent", "Any primal class", "PP"],
    ["epicdestiny286", "Fatesinger", "Bard", "PHB2"],
    ["epicdestiny338", "Feyliege", "Any arcane class; must have the fey origin, be a half-elf, or be a warlock with the fey pact", "AP"],
    ["epicdestiny452", "Free Soul", "Revenant", "Dra376"],
    ["epicdestiny504", "Fury of the Wild", "Any primal class", "PP"],
    ["epicdestiny287", "Glorious Spirit", "Any primal class", "PHB2"],
    ["epicdestiny996", "God-Emperor", "Human", "Dra411"],
    ["epicdestiny203", "Godhunter", "Ranger or rogue", "MP"],
    ["epicdestiny614", "Godmind", "Any psionic class", "PHB3"],
    ["epicdestiny765", "Grandmaster of Flowers", "Monk", "PsP"],
    ["epicdestiny840", "Guardian of the Void", "", "HoS"],
    ["epicdestiny288", "Harbinger of Doom", "", "PHB2"],
    ["epicdestiny210", "Harper of Legend", "Good or lawful good alignment; training in any two of Diplomacy, Insight, Nature, or Stealth; membership in the Harpers (see the sidebar)", "Dra367"],
    ["epicdestiny699", "Heir of Siberys", "", "Dra388"],
    ["epicdestiny572", "Heir to the Empire", "Tiefling", "PHR:T"],
    ["epicdestiny505", "Honored Ancestor", "Any primal class", "PP"],
    ["epicdestiny731", "Hordemaster", "", "DSCS"],
    ["epicdestiny339", "Immanence", "Any arcane class", "AP"],
    ["epicdestiny728", "Indomitable Champion", "", "HotFL"],
    ["epicdestiny615", "Invincible Mind", "Battlemind", "PHB3"],
    ["epicdestiny583", "Invincible Vanguard", "Any martial class", "MP2"],
    ["epicdestiny841", "Keeper of the Everflow", "", "HoS"],
    ["epicdestiny297", "Keybearer", "", "Dra372"],
    ["epicdestiny204", "Legendary General", "Warlord", "MP"],
    ["epicdestiny211", "Legendary Sovereign", "Fighter, paladin, ranger, or warlord", "MP2"],
    ["epicdestiny970", "Lord of Chaos", "", "HotEC"],
    ["epicdestiny340", "Lord of Fate", "Any arcane class, unaligned alignment", "AP"],
    ["epicdestiny289", "Lorekeeper", "Intelligence 21 or Wisdom 21, training in two knowledge skills", "PHB2"],
    ["epicdestiny341", "Magister", "Any arcane class", "AP"],
    ["epicdestiny842", "Marshal of Letherna", "", "HoS"],
    ["epicdestiny205", "Martial Archetype", "Any martial class, paragon multiclassing in a martial class", "MP"],
    ["epicdestiny845", "Master Hierophant", "Druid", "Dra396"],
    ["epicdestiny766", "Master of Moments", "Any psionic class", "PsP"],
    ["epicdestiny616", "Master of the Eternal Hunt", "Seeker", "PHB3"],
    ["epicdestiny732", "Mind Lord of the Order", "Any psionic class that uses power points", "DSCS"],
    ["epicdestiny389", "Mourning Savior", "", "EPG"],
    ["epicdestiny506", "Mythic Spirit", "Any primal class", "PP"],
    ["epicdestiny342", "Parable", "Wizard", "AP"],
    ["epicdestiny206", "Perfect Assassin", "Rogue", "MP"],
    ["epicdestiny507", "Perfect Guardian", "Warden", "PP"],
    ["epicdestiny471", "Perfect Slayer", "Assassin", "Dra379"],
    ["epicdestiny298", "Planeshaper", "", "Dra372"],
    ["epicdestiny243", "Primal Avatar", "Any primal class", "PHB2"],
    ["epicdestiny299", "Prince of Hell", "", "Dra372"],
    ["epicdestiny294", "Prison of the Winds", "", "Dra371"],
    ["epicdestiny300", "Punisher of the Gods", "", "Dra372"],
    ["epicdestiny733", "Pyreen", "Any primal class or primal theme", "DSCS"],
    ["epicdestiny157", "Radiant One", "", "Dra366"],
    ["epicdestiny346", "Raven Consort", "Shadar-kai, must worship the Raven Queen", "Dra372"],
    ["epicdestiny523", "Raven Knight", "Must worship the Raven Queen", "Dra380"],
    ["epicdestiny154", "Reborn Champion", "", "Dra365"],
    ["epicdestiny213", "Redeemed Drow", "Drow race", "Dra367"],
    ["epicdestiny508", "Reincarnate Champion", "Any primal class", "PP"],
    ["epicdestiny291", "Revered One", "Any divine class", "PHB2"],
    ["epicdestiny617", "Rune Maker", "Runepriest", "PHB3"],
    ["epicdestiny343", "Sage of Ages", "Any arcane class", "AP"],
    ["epicdestiny847", "Sage of the Swan Tower", "Must worship Ioun", "Dra397"],
    ["epicdestiny449", "Saint", "Any divine class", "DP"],
    ["epicdestiny912", "Shiradi Champion", "Any nonevil alignment", "HotF"],
    ["epicdestiny645", "Soul of the World", "Deva", "Dra385"],
    ["epicdestiny509", "Sovereign Beast", "Druid, wild shape power", "PP"],
    ["epicdestiny585", "Star-Favored Champion", "Any martial class", "MP2"],
    ["epicdestiny301", "Storm Sovereign", "", "Dra372"],
    ["epicdestiny390", "Sublime Flame", "Any divine class, must worship the Silver Flame", "EPG"],
    ["epicdestiny697", "Thief of Legend", "Trained in Stealth, Thievery", "Dra388"],
    ["epicdestiny767", "Topaz Crusader", "Any psionic class, Psionic Augmentation class feature", "PsP"],
    ["epicdestiny843", "Twilight Tribune", "", "HoS"],
    ["epicdestiny207", "Undying Warrior", "Fighter", "MP"],
    ["epicdestiny698", "Unyielding Sentinel", "Any defender class", "Dra388"],
    ["epicdestiny618", "War Master", "Ardent", "PHB3"],
    ["epicdestiny208", "Warmaster", "Warlord", "MP"],
    ["epicdestiny913", "Wild Hunter", "", "HotF"],
    ["epicdestiny302", "Winter Sovereign", "Fey origin", "Dra372"],
    ["epicdestiny914", "Witch Queen", "Wizard", "HotF"],
    ["epicdestiny510", "World Tree Guardian", "Any primal class", "PP"]
])