od.reader.jsonp_data_listing(20130703, "disease", ["ID", "Name", "Level", "SourceBook"], [
    ["disease79", "Corporeal Instability", "", "The Book of Vile Darkness"],
    ["disease73", "Deathsong", "", "The Book of Vile Darkness"],
    ["disease74", "Demon Fever", "", "The Book of Vile Darkness"],
    ["disease75", "Faceless Hate", "", "The Book of Vile Darkness"],
    ["disease70", "Foul Rotting", "", "MME"],
    ["disease76", "Melting Fury", "", "The Book of Vile Darkness"],
    ["disease77", "Psychic Parasites", "", "The Book of Vile Darkness"],
    ["disease78", "Scarlet Plague", "", "The Book of Vile Darkness"],
    ["disease19", "Dire Rat Filth Fever", "1", "MV, Dun182"],
    ["disease92", "Slight Filth Fever", "1", "Dun211"],
    ["disease45", "Skinrot", "2", "Open Grave"],
    ["disease94", "Lesser Abyssal Plague", "3", "Dun214"],
    ["disease11", "Wererat Filth Fever", "3", "MV"],
    ["disease41", "Rot Grub Infestation", "4", "MM3, The Book of Vile Darkness"],
    ["disease80", "Whispering Madness", "4", "Dun195"],
    ["disease63", "Creeping Madness", "5", "NCS"],
    ["disease60", "Demon Pox", "5", "TPB"],
    ["disease21", "Feral Wererat Filth Fever", "5", "Dun185"],
    ["disease23", "Filth Fever", "5", "Dun181"],
    ["disease91", "Russet Mold Contagion", "5", "Dun201"],
    ["disease36", "Moontusk Fever", "6", "MM2, Dun181"],
    ["disease46", "Slavering Canker", "6", "MM2"],
    ["disease52", "Wereboar Moontusk Fever", "6", "Dun210"],
    ["disease54", "Werewolf Moon Frenzy", "6", "MV, Dun185"],
    ["disease81", "Dusanu Rot", "7", "Dun195"],
    ["disease29", "Lesser Otyugh Filth Fever", "7", "MV, TS"],
    ["disease53", "Wereserpent Blood Rot", "7", "Dun185"],
    ["disease59", "Abyssal Plague", "8", "MV:TttNV, Madness at Gardmore Abbey, Halls of Undermountain"],
    ["disease64", "Charnel Fields Filth Fever", "8", "NCS"],
    ["disease30", "Lockjaw", "8", "Dun178"],
    ["disease34", "Moon Frenzy", "8", "Dun156"],
    ["disease42", "Rusty Paralysis", "8", "Dra376"],
    ["disease93", "Werewolf Lycanthropy", "8", "Dun214"],
    ["disease13", "Blinding Sickness", "9", "DMG"],
    ["disease20", "Echo Madness", "9", "Underdark"],
    ["disease31", "Meenlock Corruption", "9", "MM3, Dun190"],
    ["disease62", "Blistering Corruption", "10", "MV:TttNV"],
    ["disease22", "Festering Doom", "10", "Dun161"],
    ["disease27", "Greater Werewolf Moon Frenzy", "10", "Dun185"],
    ["disease83", "Wastelands Sickness", "10", "Demonomicon"],
    ["disease17", "Cemetery Rot", "11", "Open Grave"],
    ["disease26", "Greater Otyugh Filth Fever", "11", "MV"],
    ["disease58", "Mistwatch Blight", "11", "Dun186"],
    ["disease35", "Moon Rage", "11", "MM2"],
    ["disease37", "Mournland Affliction", "11", "ECS"],
    ["disease48", "Soul Rot", "11", "MotP"],
    ["disease56", "Worms of Kyuss", "11", "Exemplars of Evil"],
    ["disease14", "Brain Fluke", "12", "FRCG"],
    ["disease16", "Cackle Fever", "12", "DMG"],
    ["disease51", "Twisted Domination", "12", "Dun157"],
    ["disease65", "Cerebral Parasites", "13", "Dun192"],
    ["disease66", "Greater Abyssal Plague", "13", "Dun192"],
    ["disease25", "Greater Moon Frenzy", "13", "MM2, Dun197"],
    ["disease43", "Sewer Fever", "13", "DMG2"],
    ["disease24", "Filth Plague", "14", "ECS, Dun177"],
    ["disease44", "Shakes", "14", "DMG"],
    ["disease86", "Slime Lord's Rot", "14", "Demonomicon"],
    ["disease82", "Screaming Scalepox", "15", "Demonomicon"],
    ["disease18", "Chaos Phage", "16", "MM3, TPB, Dun179"],
    ["disease33", "Mindfire", "16", "DMG"],
    ["disease50", "Touch of Kyuss", "16", "MM3, Dun188"],
    ["disease61", "Spider Queen's Curse", "17", "MV:TttNV"],
    ["disease15", "Brood Fever", "21", "Elder Evils"],
    ["disease28", "Hellfever", "21", "DMG"],
    ["disease38", "Mummy Rot", "21", "Draco: Metallic, DMG, Open Grave"],
    ["disease47", "Slimy Doom", "23", "DMG"],
    ["disease90", "Silvery Sleep", "26", "Open Grave"],
    ["disease85", "Flesh Warp", "28", "Demonomicon"],
    ["disease84", "Wasting Plague", "31", "Demonomicon"]
])