od.reader.jsonp_data_listing(20130703, "class", ["ID", "Name", "RoleName", "PowerSourceText", "KeyAbilities", "SourceBook"], [
    ["class529", "Ardent", "Leader", "Psionic", "Cha", "PHB3"],
    ["class125", "Artificer", "Leader", "Arcane", "Int", "EPG"],
    ["class466", "Assassin", "Striker", "Shadow", "Dex", "Dra379"],
    ["class811", "Assassin (Executioner)", "Striker", "Martial and Shadow", "Dex", "HoS"],
    ["class129", "Avenger", "Striker", "Divine", "Wis", "PHB2"],
    ["class148", "Barbarian", "Striker", "Primal", "Str", "PHB2"],
    ["class906", "Barbarian (Berserker)", "Defender and Striker", "Martial and Primal", "Str", "HotF"],
    ["class104", "Bard", "Leader", "Arcane", "Cha", "PHB2"],
    ["class907", "Bard (Skald)", "Leader", "Arcane and Martial", "Cha", "HotF"],
    ["class124", "Battlemind", "Defender", "Psionic", "Con", "PHB3"],
    ["class2", "Cleric (Templar)", "Leader", "Divine", "Str, Wis", "PHB"],
    ["class705", "Cleric (Warpriest)", "Leader", "Divine", "Wis", "HotFL"],
    ["class126", "Druid", "Controller", "Primal", "Wis", "PHB2"],
    ["class909", "Druid (Protector)", "Controller", "Primal", "Wis", "HotF"],
    ["class779", "Druid (Sentinel)", "Leader", "Primal", "Wis", "HotFK"],
    ["class713", "Fighter (Knight)", "Defender", "Martial", "Str", "HotFL"],
    ["class716", "Fighter (Slayer)", "Striker", "Martial", "Str", "HotFL"],
    ["class3", "Fighter (Weaponmaster)", "Defender", "Martial", "Str", "PHB"],
    ["class127", "Invoker", "Controller", "Divine", "Wis", "PHB2"],
    ["class362", "Monk", "Striker", "Psionic", "Dex", "PHB3"],
    ["class4", "Paladin", "Defender", "Divine", "Str, Cha", "PHB"],
    ["class813", "Paladin (Blackguard)", "Striker", "Divine", "Str", "HoS"],
    ["class784", "Paladin (Cavalier)", "Defender", "Divine", "Str", "HotFK"],
    ["class437", "Psion", "Controller", "Psionic", "Int", "PHB3"],
    ["class5", "Ranger", "Striker", "Martial", "Str, Dex", "PHB"],
    ["class788", "Ranger (Hunter)", "Controller", "Martial and Primal", "Dex or Str", "HotFK"],
    ["class790", "Ranger (Scout)", "Striker", "Martial and Primal", "Dex", "HotFK"],
    ["class6", "Rogue (Scoundrel)", "Striker", "Martial", "Dex", "PHB"],
    ["class719", "Rogue (Thief)", "Striker", "Martial", "Dex or Str", "HotFL"],
    ["class602", "Runepriest", "Leader", "Divine", "Str", "PHB3"],
    ["class472", "Seeker", "Controller", "Primal", "Wis", "PHB3"],
    ["class147", "Shaman", "Leader", "Primal", "Wis", "PHB2"],
    ["class128", "Sorcerer", "Striker", "Arcane", "Cha", "PHB2"],
    ["class956", "Sorcerer (Elementalist)", "Striker", "Arcane", "Cha", "HotEC"],
    ["class53", "Swordmage", "Defender", "Arcane", "Int", "FRPG"],
    ["class817", "Vampire", "Striker", "Shadow", "Dex", "HoS"],
    ["class134", "Warden", "Defender", "Primal", "Str", "PHB2"],
    ["class7", "Warlock", "Striker", "Arcane", "Con, Cha", "PHB"],
    ["class821", "Warlock (Binder)", "Controller", "Arcane", "Cha", "HoS"],
    ["class793", "Warlock (Hexblade)", "Striker", "Arcane", "Cha", "HotFK"],
    ["class8", "Warlord (Marshal)", "Leader", "Martial", "Str", "PHB"],
    ["class9", "Wizard (Arcanist)", "Controller", "Arcane", "Int", "PHB"],
    ["class883", "Wizard (Bladesinger)", "Controller", "Arcane", "Int", "NCS"],
    ["class722", "Wizard (Mage)", "Controller", "Arcane", "Int", "HotFL"],
    ["class958", "Wizard (Sha'ir)", "Controller", "Arcane", "Int", "HotEC"],
    ["class908", "Wizard (Witch)", "Controller", "Arcane", "Int", "HotF"],
    ["class588", "Hybrid Ardent", "Leader", "Psionic", "Cha", "PHB3"],
    ["class536", "Hybrid Artificer", "Leader", "Arcane", "Int", "PHB3"],
    ["class641", "Hybrid Assassin", "Striker", "Shadow", "Dex", "Dra385"],
    ["class891", "Hybrid Assassin (Executioner)", "Striker", "Martial and Shadow", "Dex", "Dra400"],
    ["class439", "Hybrid Avenger", "Striker", "Divine", "Wis", "PHB3"],
    ["class440", "Hybrid Barbarian", "Striker", "Primal", "Str", "PHB3"],
    ["class441", "Hybrid Bard", "Leader", "Arcane", "Cha", "PHB3"],
    ["class590", "Hybrid Battlemind", "Defender", "Psionic", "Con", "PHB3"],
    ["class352", "Hybrid Cleric", "Leader", "Divine", "Str, Wis", "PHB3"],
    ["class442", "Hybrid Druid", "Controller", "Primal", "Wis", "PHB3"],
    ["class894", "Hybrid Druid (Sentinel)", "Leader", "Primal", "Wis", "Dra400"],
    ["class353", "Hybrid Fighter", "Defender", "Martial", "Str", "PHB3"],
    ["class443", "Hybrid Invoker", "Controller", "Divine", "Wis", "PHB3"],
    ["class609", "Hybrid Monk", "Striker", "Psionic", "Dex", "PHB3"],
    ["class354", "Hybrid Paladin", "Defender", "Divine", "Str, Cha", "PHB3"],
    ["class892", "Hybrid Paladin (Blackguard)", "Striker", "Divine", "Str, Cha", "Dra400"],
    ["class895", "Hybrid Paladin (Cavalier)", "Defender", "Divine", "Str, Cha", "Dra400"],
    ["class610", "Hybrid Psion", "Controller", "Psionic", "Int", "PHB3"],
    ["class355", "Hybrid Ranger", "Striker", "Martial", "Str, Dex", "PHB3"],
    ["class356", "Hybrid Rogue", "Striker", "Martial", "Dex", "PHB3"],
    ["class611", "Hybrid Runepriest", "Leader", "Divine", "Str", "PHB3"],
    ["class612", "Hybrid Seeker", "Controller", "Primal", "Wis", "PHB3"],
    ["class444", "Hybrid Shaman", "Leader", "Primal", "Wis", "PHB3"],
    ["class445", "Hybrid Sorcerer", "Striker", "Arcane", "Cha", "PHB3"],
    ["class357", "Hybrid Swordmage", "Defender", "Arcane", "Int", "PHB3"],
    ["class893", "Hybrid Vampire", "Striker", "Shadow", "Dex", "Dra400"],
    ["class446", "Hybrid Warden", "Defender", "Primal", "Str", "PHB3"],
    ["class358", "Hybrid Warlock", "Striker", "Arcane", "Con, Cha", "PHB3"],
    ["class896", "Hybrid Warlock (Binder)", "Controller", "Arcane", "Con, Cha", "Dra400"],
    ["class359", "Hybrid Warlord", "Leader", "Martial", "Str", "PHB3"],
    ["class360", "Hybrid Wizard", "Controller", "Arcane", "Int", "PHB3"]
])